(function initLinkPreviewTester(root) {
    "use strict";
    const panel = document.getElementById("link-preview-tester"); if (!panel) return;
    const el = {}; ["link-preview-form","link-preview-input","link-preview-error","link-preview-results","link-preview-state","link-preview-missing-count","link-preview-meta-list","link-preview-domain","link-preview-card-title","link-preview-card-description","link-preview-image","link-preview-image-fallback","link-preview-live"].forEach((id)=>{el[id]=document.getElementById(id);});
    el["link-preview-form"].addEventListener("submit", async (event)=>{event.preventDefault(); await inspect();});
    el["link-preview-image"].addEventListener("error",()=>{el["link-preview-image"].hidden=true;el["link-preview-image-fallback"].hidden=false;});
    async function inspect(){ const raw=el["link-preview-input"].value.trim(); let url; try { url=new URL(/^https?:\/\//i.test(raw)?raw:`https://${raw}`); if(!["http:","https:"].includes(url.protocol)) throw new Error(); } catch { return showError("Geçerli bir HTTP veya HTTPS URL’si girin. Örnek: https://ornek.com"); } clearError(); el["link-preview-state"].textContent="Kontrol ediliyor"; try { const response=await fetch(url.href,{mode:"cors",credentials:"omit",redirect:"follow"}); if(!response.ok) throw new Error(`Sunucu ${response.status} yanıtı verdi.`); const html=await response.text(); const data=parseMetadata(html,response.url||url.href); render(data); } catch(error) { showError(`Metadata alınamadı. Bu site tarayıcıdan gelen isteklere CORS izni vermiyor olabilir. ${error.message||""}`.trim()); } }
    function parseMetadata(html,baseUrl){const doc=new DOMParser().parseFromString(html,"text/html");const get=(selectors)=>{for(const selector of selectors){const node=doc.querySelector(selector);const value=node?.getAttribute("content")||node?.getAttribute("href")||node?.textContent;if(value?.trim())return value.trim();}return "";};const absolute=(value)=>{try{return value?new URL(value,baseUrl).href:"";}catch{return value||"";}};return {url:baseUrl,title:get(['meta[property="og:title"]','meta[name="twitter:title"]','title']),description:get(['meta[property="og:description"]','meta[name="twitter:description"]','meta[name="description"]']),ogImage:absolute(get(['meta[property="og:image"]','meta[name="twitter:image"]'])),favicon:absolute(get(['link[rel~="icon"]','link[rel="shortcut icon"]'])),canonical:absolute(get(['link[rel="canonical"]'])),twitter:get(['meta[name="twitter:card"]']),ogType:get(['meta[property="og:type"]'])};}
    function render(data){const host=new URL(data.url).hostname;const rows=[["Title",data.title],["Description",data.description],["Open Graph image",data.ogImage],["Favicon",data.favicon],["Canonical URL",data.canonical],["Twitter Card",data.twitter],["OG type",data.ogType]];const missing=rows.filter(([,value])=>!value).length;el["link-preview-domain"].textContent=host;el["link-preview-card-title"].textContent=data.title||"Başlık bulunamadı";el["link-preview-card-description"].textContent=data.description||"Açıklama bulunamadı.";el["link-preview-image"].hidden=!data.ogImage;el["link-preview-image-fallback"].hidden=Boolean(data.ogImage);if(data.ogImage)el["link-preview-image"].src=data.ogImage;el["link-preview-meta-list"].replaceChildren(...rows.map(([label,value])=>{const row=document.createElement("div");if(!value)row.className="is-missing";const term=document.createElement("dt");term.textContent=label;const description=document.createElement("dd");description.textContent=value||"Eksik";row.append(term,description);return row;}));el["link-preview-state"].textContent="Bulundu";el["link-preview-missing-count"].textContent=missing?`${missing} eksik`:"Tam";el["link-preview-results"].hidden=false;announce(missing?`${missing} metadata alanı eksik.`:"Tüm temel metadata alanları bulundu.");}
    function showError(message){el["link-preview-results"].hidden=true;el["link-preview-error"].textContent=message;el["link-preview-error"].hidden=false;announce(message);}function clearError(){el["link-preview-error"].hidden=true;}function announce(message){el["link-preview-live"].textContent=message;}
}(window));
