(function initializeUsernameSearchPlatforms(global) {
    "use strict";

    const CORS_LIMITATION = "GitHub Pages üzerinden güvenilir bir CORS/API kontrolü yapılamıyor.";
    const AUTH_LIMITATION = "Güvenilir kullanıcı kontrolü API anahtarı veya kimlik doğrulaması gerektiriyor.";
    const SIMPLE_ICONS_VERSION = "13.21.0";
    const simpleIcon = (slug) => `https://cdn.jsdelivr.net/npm/simple-icons@${SIMPLE_ICONS_VERSION}/icons/${slug}.svg`;

    const platforms = [
        {
            id: "github",
            name: "GitHub",
            priority: 100,
            profileUrl: "https://github.com/{username}",
            iconUrl: simpleIcon("github"),
            usernamePattern: "^[A-Za-z0-9](?:[A-Za-z0-9]|-(?=[A-Za-z0-9])){0,38}$",
            detection: {
                method: "fetch",
                requestUrl: "https://api.github.com/users/{username}",
                evaluator: "jsonExact",
                identityPath: "login",
                notFoundStatuses: [404],
            },
        },
        {
            id: "reddit",
            name: "Reddit",
            priority: 99,
            profileUrl: "https://www.reddit.com/user/{username}",
            iconUrl: simpleIcon("reddit"),
            usernamePattern: "^[A-Za-z0-9_-]{3,20}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "instagram",
            name: "Instagram",
            priority: 98,
            profileUrl: "https://www.instagram.com/{username}/",
            iconUrl: simpleIcon("instagram"),
            usernamePattern: "^[A-Za-z0-9._]{1,30}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "tiktok",
            name: "TikTok",
            priority: 97,
            profileUrl: "https://www.tiktok.com/@{username}",
            iconUrl: simpleIcon("tiktok"),
            usernamePattern: "^[A-Za-z0-9._]{2,24}$",
            detection: {
                method: "fetch",
                requestUrl: "https://www.tiktok.com/oembed?url=https%3A%2F%2Fwww.tiktok.com%2F%40{username}",
                evaluator: "oembedExact",
                identityPath: "author_url",
                missingCodePath: "code",
                missingCode: 400,
            },
        },
        {
            id: "youtube",
            name: "YouTube",
            priority: 96,
            profileUrl: "https://www.youtube.com/@{username}",
            iconUrl: simpleIcon("youtube"),
            usernamePattern: "^[A-Za-z0-9._-]{3,30}$",
            detection: {
                method: "unavailable",
                reason: "YouTube oEmbed kanalları doğrulamıyor; Data API ise anahtar gerektiriyor.",
            },
        },
        {
            id: "x",
            name: "X",
            priority: 95,
            profileUrl: "https://x.com/{username}",
            iconUrl: simpleIcon("x"),
            usernamePattern: "^[A-Za-z0-9_]{1,15}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "facebook",
            name: "Facebook",
            priority: 94,
            profileUrl: "https://www.facebook.com/{username}",
            iconUrl: simpleIcon("facebook"),
            usernamePattern: "^[A-Za-z0-9.]{5,50}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "linkedin",
            name: "LinkedIn",
            priority: 94,
            profileUrl: "https://www.linkedin.com/in/{username}",
            iconUrl: simpleIcon("linkedin"),
            usernamePattern: "^[A-Za-z0-9][A-Za-z0-9-]{2,63}$",
            detection: {
                method: "unavailable",
                reason: "LinkedIn profil kontrolü CORS nedeniyle güvenilir biçimde yalnızca backend üzerinden yapılabiliyor.",
            },
        },
        {
            id: "twitch",
            name: "Twitch",
            priority: 93,
            profileUrl: "https://www.twitch.tv/{username}",
            iconUrl: simpleIcon("twitch"),
            usernamePattern: "^[A-Za-z0-9_]{3,25}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "pinterest",
            name: "Pinterest",
            priority: 92,
            profileUrl: "https://www.pinterest.com/{username}/",
            iconUrl: simpleIcon("pinterest"),
            usernamePattern: "^[A-Za-z0-9_]{3,30}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "gitlab",
            name: "GitLab",
            priority: 91,
            profileUrl: "https://gitlab.com/{username}",
            iconUrl: simpleIcon("gitlab"),
            usernamePattern: "^[A-Za-z0-9](?:[A-Za-z0-9._-]{0,253}[A-Za-z0-9_])?$",
            detection: {
                method: "fetch",
                requestUrl: "https://gitlab.com/api/v4/users?username={username}",
                evaluator: "jsonArrayExact",
                identityPath: "username",
            },
        },
        {
            id: "codeberg",
            name: "Codeberg",
            priority: 90,
            profileUrl: "https://codeberg.org/{username}",
            iconUrl: simpleIcon("codeberg"),
            usernamePattern: "^[A-Za-z0-9][A-Za-z0-9._-]{0,38}$",
            detection: {
                method: "fetch",
                requestUrl: "https://codeberg.org/api/v1/users/{username}",
                evaluator: "jsonExact",
                identityPath: "login",
                notFoundStatuses: [404],
            },
        },
        {
            id: "gitea",
            name: "Gitea.com",
            priority: 89,
            profileUrl: "https://gitea.com/{username}",
            iconUrl: simpleIcon("gitea"),
            usernamePattern: "^[A-Za-z0-9][A-Za-z0-9._-]{0,38}$",
            detection: {
                method: "fetch",
                requestUrl: "https://gitea.com/api/v1/users/{username}",
                evaluator: "jsonExact",
                identityPath: "login",
                notFoundStatuses: [404],
            },
        },
        {
            id: "bitbucket",
            name: "Bitbucket",
            priority: 88,
            profileUrl: "https://bitbucket.org/{username}/",
            iconUrl: simpleIcon("bitbucket"),
            usernamePattern: "^[A-Za-z0-9_-]{1,30}$",
            detection: {
                method: "fetch",
                requestUrl: "https://api.bitbucket.org/2.0/workspaces/{username}",
                evaluator: "jsonExact",
                identityPath: "slug",
                notFoundStatuses: [404],
            },
        },
        {
            id: "dev-community",
            name: "DEV Community",
            priority: 87,
            profileUrl: "https://dev.to/{username}",
            iconUrl: simpleIcon("devdotto"),
            usernamePattern: "^[A-Za-z0-9_-]{1,30}$",
            detection: {
                method: "fetch",
                requestUrl: "https://dev.to/api/users/by_username?url={username}",
                evaluator: "jsonExact",
                identityPath: "username",
                notFoundStatuses: [404],
            },
        },
        {
            id: "hacker-news",
            name: "Hacker News",
            priority: 86,
            profileUrl: "https://news.ycombinator.com/user?id={username}",
            iconUrl: simpleIcon("ycombinator"),
            usernamePattern: "^[A-Za-z0-9_-]{2,15}$",
            detection: {
                method: "fetch",
                requestUrl: "https://hacker-news.firebaseio.com/v0/user/{username}.json",
                evaluator: "nullableJsonExact",
                identityPath: "id",
            },
        },
        {
            id: "medium",
            name: "Medium",
            priority: 85,
            profileUrl: "https://medium.com/@{username}",
            iconUrl: simpleIcon("medium"),
            usernamePattern: "^[A-Za-z0-9_-]{1,30}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "bluesky",
            name: "Bluesky",
            priority: 84,
            profileUrl: "https://bsky.app/profile/{username}.bsky.social",
            iconUrl: simpleIcon("bluesky"),
            usernamePattern: "^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$",
            detection: {
                method: "fetch",
                requestUrl: "https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor={username}.bsky.social",
                evaluator: "bluesky",
            },
        },
        {
            id: "mastodon",
            name: "Mastodon.social",
            priority: 83,
            profileUrl: "https://mastodon.social/@{username}",
            iconUrl: simpleIcon("mastodon"),
            usernamePattern: "^[A-Za-z0-9_]{1,30}$",
            detection: {
                method: "fetch",
                requestUrl: "https://mastodon.social/api/v1/accounts/lookup?acct={username}",
                evaluator: "jsonExact",
                identityPath: "username",
                notFoundStatuses: [404],
            },
        },
        {
            id: "threads",
            name: "Threads",
            priority: 82,
            profileUrl: "https://www.threads.net/@{username}",
            iconUrl: simpleIcon("threads"),
            usernamePattern: "^[A-Za-z0-9._]{1,30}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "telegram",
            name: "Telegram",
            priority: 81,
            profileUrl: "https://t.me/{username}",
            iconUrl: simpleIcon("telegram"),
            usernamePattern: "^[A-Za-z][A-Za-z0-9_]{4,31}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "soundcloud",
            name: "SoundCloud",
            priority: 80,
            profileUrl: "https://soundcloud.com/{username}",
            iconUrl: simpleIcon("soundcloud"),
            usernamePattern: "^[A-Za-z0-9_-]{1,50}$",
            detection: {
                method: "fetch",
                requestUrl: "https://soundcloud.com/oembed?format=json&url=https%3A%2F%2Fsoundcloud.com%2F{username}",
                evaluator: "oembedExact",
                identityPath: "author_url",
                notFoundStatuses: [404],
            },
        },
        {
            id: "spotify",
            name: "Spotify",
            priority: 79,
            profileUrl: "https://open.spotify.com/user/{username}",
            iconUrl: simpleIcon("spotify"),
            usernamePattern: "^[A-Za-z0-9._-]{1,64}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "vimeo",
            name: "Vimeo",
            priority: 78,
            profileUrl: "https://vimeo.com/{username}",
            iconUrl: simpleIcon("vimeo"),
            usernamePattern: "^[A-Za-z0-9_-]{1,64}$",
            detection: {
                method: "unavailable",
                reason: "Vimeo oEmbed profil sayfalarını doğrulamıyor; API erişimi kimlik doğrulaması gerektiriyor.",
            },
        },
        {
            id: "steam",
            name: "Steam",
            priority: 77,
            profileUrl: "https://steamcommunity.com/id/{username}",
            iconUrl: simpleIcon("steam"),
            usernamePattern: "^[A-Za-z0-9_-]{2,32}$",
            detection: { method: "unavailable", reason: AUTH_LIMITATION },
        },
        {
            id: "keybase",
            name: "Keybase",
            priority: 76,
            profileUrl: "https://keybase.io/{username}",
            iconUrl: simpleIcon("keybase"),
            usernamePattern: "^[A-Za-z0-9_]{2,16}$",
            detection: {
                method: "fetch",
                requestUrl: "https://keybase.io/_/api/1.0/user/lookup.json?username={username}",
                evaluator: "keybase",
            },
        },
        {
            id: "deviantart",
            name: "DeviantArt",
            priority: 75,
            profileUrl: "https://www.deviantart.com/{username}",
            iconUrl: simpleIcon("deviantart"),
            usernamePattern: "^[A-Za-z][A-Za-z0-9_-]{2,19}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "flickr",
            name: "Flickr",
            priority: 74,
            profileUrl: "https://www.flickr.com/people/{username}",
            iconUrl: simpleIcon("flickr"),
            usernamePattern: "^[A-Za-z0-9@._-]{1,64}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "tumblr",
            name: "Tumblr",
            priority: 73,
            profileUrl: "https://{username}.tumblr.com/",
            iconUrl: simpleIcon("tumblr"),
            usernamePattern: "^[A-Za-z0-9-]{1,32}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "about-me",
            name: "About.me",
            priority: 72,
            profileUrl: "https://about.me/{username}",
            iconUrl: simpleIcon("aboutdotme"),
            usernamePattern: "^[A-Za-z0-9_-]{1,30}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "last-fm",
            name: "Last.fm",
            priority: 71,
            profileUrl: "https://www.last.fm/user/{username}",
            iconUrl: simpleIcon("lastdotfm"),
            usernamePattern: "^[A-Za-z0-9_-]{2,15}$",
            detection: {
                method: "unavailable",
                reason: "Last.fm kullanıcı kontrolü resmi API anahtarının Worker secret'ı olarak yapılandırılmasını gerektiriyor.",
            },
        },
        {
            id: "docker-hub",
            name: "Docker Hub",
            priority: 70,
            profileUrl: "https://hub.docker.com/u/{username}",
            iconUrl: simpleIcon("docker"),
            usernamePattern: "^[a-z0-9][a-z0-9_-]{1,29}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
        {
            id: "npm",
            name: "npm",
            priority: 69,
            profileUrl: "https://www.npmjs.com/~{username}",
            iconUrl: simpleIcon("npm"),
            usernamePattern: "^[a-z0-9][a-z0-9._-]{0,63}$",
            detection: {
                method: "fetch",
                requestUrl: "https://registry.npmjs.org/-/v1/search?text=maintainer%3A{username}&size=1",
                evaluator: "npmMaintainer",
            },
        },
        {
            id: "scratch",
            name: "Scratch",
            priority: 68,
            profileUrl: "https://scratch.mit.edu/users/{username}/",
            iconUrl: simpleIcon("scratch"),
            usernamePattern: "^[A-Za-z0-9_-]{3,20}$",
            detection: {
                method: "unavailable",
                reason: "Scratch API yalnızca Scratch origin'ine CORS izni veriyor.",
            },
        },
        {
            id: "codeforces",
            name: "Codeforces",
            priority: 67,
            profileUrl: "https://codeforces.com/profile/{username}",
            iconUrl: simpleIcon("codeforces"),
            usernamePattern: "^[A-Za-z0-9_.-]{3,24}$",
            detection: {
                method: "fetch",
                requestUrl: "https://codeforces.com/api/user.info?handles={username}&checkHistoricHandles=false",
                evaluator: "codeforces",
            },
        },
        {
            id: "codewars",
            name: "Codewars",
            priority: 66,
            profileUrl: "https://www.codewars.com/users/{username}",
            iconUrl: simpleIcon("codewars"),
            usernamePattern: "^[A-Za-z0-9_-]{1,50}$",
            detection: {
                method: "fetch",
                requestUrl: "https://www.codewars.com/api/v1/users/{username}",
                evaluator: "jsonExact",
                identityPath: "username",
                notFoundStatuses: [404],
            },
        },
        {
            id: "chess-com",
            name: "Chess.com",
            priority: 65,
            profileUrl: "https://www.chess.com/member/{username}",
            iconUrl: simpleIcon("chessdotcom"),
            usernamePattern: "^[A-Za-z0-9_-]{3,25}$",
            detection: {
                method: "fetch",
                requestUrl: "https://api.chess.com/pub/player/{username}",
                evaluator: "jsonExact",
                identityPath: "username",
                notFoundStatuses: [404],
            },
        },
        {
            id: "lichess",
            name: "Lichess",
            priority: 64,
            profileUrl: "https://lichess.org/@/{username}",
            iconUrl: simpleIcon("lichess"),
            usernamePattern: "^[A-Za-z0-9_-]{2,30}$",
            detection: {
                method: "fetch",
                requestUrl: "https://lichess.org/api/user/{username}",
                evaluator: "jsonExact",
                identityPath: "username",
                notFoundStatuses: [404],
            },
        },
        {
            id: "mixcloud",
            name: "Mixcloud",
            priority: 63,
            profileUrl: "https://www.mixcloud.com/{username}/",
            iconUrl: simpleIcon("mixcloud"),
            usernamePattern: "^[A-Za-z0-9_-]{1,30}$",
            detection: {
                method: "fetch",
                requestUrl: "https://api.mixcloud.com/{username}/",
                evaluator: "jsonExact",
                identityPath: "username",
                notFoundStatuses: [404],
            },
        },
        {
            id: "gravatar",
            name: "Gravatar",
            priority: 62,
            profileUrl: "https://gravatar.com/{username}",
            iconUrl: simpleIcon("gravatar"),
            usernamePattern: "^[A-Za-z0-9._-]{1,64}$",
            detection: {
                method: "fetch",
                requestUrl: "https://en.gravatar.com/{username}.json",
                evaluator: "gravatar",
                notFoundStatuses: [404],
            },
        },
        {
            id: "matrix",
            name: "Matrix.org",
            priority: 61,
            profileUrl: "https://matrix.to/#/@{username}:matrix.org",
            iconUrl: simpleIcon("matrix"),
            usernamePattern: "^[A-Za-z0-9._=-]{1,64}$",
            detection: {
                method: "fetch",
                requestUrl: "https://matrix.org/_matrix/client/v3/profile/%40{username}%3Amatrix.org",
                evaluator: "status",
                notFoundStatuses: [404],
            },
        },
        {
            id: "pixelfed",
            name: "Pixelfed.social",
            priority: 60,
            profileUrl: "https://pixelfed.social/{username}",
            iconUrl: simpleIcon("pixelfed"),
            usernamePattern: "^[A-Za-z0-9_]{1,30}$",
            detection: {
                method: "fetch",
                requestUrl: "https://pixelfed.social/api/v1/accounts/lookup?acct={username}",
                evaluator: "pixelfed",
            },
        },
        {
            id: "lemmy",
            name: "Lemmy.world",
            priority: 59,
            profileUrl: "https://lemmy.world/u/{username}",
            iconUrl: simpleIcon("lemmy"),
            usernamePattern: "^[A-Za-z0-9_]{3,20}$",
            detection: {
                method: "fetch",
                requestUrl: "https://lemmy.world/api/v3/user?username={username}",
                evaluator: "lemmy",
                notFoundStatuses: [404],
            },
        },
        {
            id: "peertube",
            name: "PeerTube.tv",
            priority: 58,
            profileUrl: "https://peertube.tv/accounts/{username}",
            iconUrl: simpleIcon("peertube"),
            usernamePattern: "^[A-Za-z0-9._-]{1,50}$",
            detection: {
                method: "fetch",
                requestUrl: "https://peertube.tv/api/v1/accounts/{username}",
                evaluator: "jsonExact",
                identityPath: "name",
                notFoundStatuses: [404],
            },
        },
        {
            id: "liberapay",
            name: "Liberapay",
            priority: 57,
            profileUrl: "https://liberapay.com/{username}/",
            iconUrl: simpleIcon("liberapay"),
            usernamePattern: "^[A-Za-z0-9_-]{1,32}$",
            detection: {
                method: "fetch",
                requestUrl: "https://liberapay.com/{username}/public.json",
                evaluator: "status",
                notFoundStatuses: [404],
            },
        },
        {
            id: "linktree",
            name: "Linktree",
            priority: 56,
            profileUrl: "https://linktr.ee/{username}",
            iconUrl: simpleIcon("linktree"),
            usernamePattern: "^[A-Za-z0-9._-]{1,30}$",
            detection: { method: "unavailable", reason: CORS_LIMITATION },
        },
    ];

    const ids = new Set();
    platforms.forEach((platform) => {
        if (ids.has(platform.id)) throw new Error(`Tekrarlanan platform kimliği: ${platform.id}`);
        ids.add(platform.id);
        Object.freeze(platform.detection);
        Object.freeze(platform);
    });

    global.UsernameSearchPlatforms = Object.freeze(platforms);
})(typeof window !== "undefined" ? window : globalThis);
