window.ParollaQuestions = [
    { letter: "A", question: "Türkiye'nin başkenti olan şehir?", answers: ["ankara"], points: 10 },
    { letter: "A", question: "gökyüzünü inceleyen bilim dalı?", answers: ["astronomi"], points: 10 },
    { letter: "A", question: "yemeklere keskin tat veren bir lezzet?", answers: ["acı"], points: 10 },
    { letter: "A", question: "düşünce ve duyguları anlatan yazılı ürün?", answers: ["anlatı"], points: 10 },
    { letter: "A", question: "eski çağlardan kalma nesne?", answers: ["antik"], points: 10 },

    { letter: "B", question: "denizde yaşayan büyük memeli?", answers: ["balina"], points: 10 },
    { letter: "B", question: "para işlemlerinin yapıldığı kurum?", answers: ["banka"], points: 10 },
    { letter: "B", question: "masallarda sihir kullanan kişi?", answers: ["büyücü"], points: 10 },
    { letter: "B", question: "yazın sık tüketilen kırmızı meyve?", answers: ["böğürtlen"], points: 10 },
    { letter: "B", question: "insanın topluluk içindeki ayrı kişiliği?", answers: ["birey"], points: 10 },

    { letter: "C", question: "soruya verilen karşılık?", answers: ["cevap"], points: 10 },
    { letter: "C", question: "sert kabuklu bir yemiş?", answers: ["ceviz"], points: 10 },
    { letter: "C", question: "topluluk veya çevre anlamına gelen kelime?", answers: ["camia"], points: 10 },
    { letter: "C", question: "çok genç bebek anlamına gelen kelime?", answers: ["cenin"], points: 10 },
    { letter: "C", question: "fiziksel nesne veya varlık?", answers: ["cisim"], points: 10 },

    { letter: "Ç", question: "sıcak içilen ve Türkiye'de çok tüketilen içecek?", answers: ["çay"], points: 10 },
    { letter: "Ç", question: "bitkinin renkli ve kokulu bölümü?", answers: ["çiçek"], points: 10 },
    { letter: "Ç", question: "çorba içmeye yarayan mutfak eşyası?", answers: ["çorba", "kaşık"], points: 10 },
    { letter: "Ç", question: "etrafı kapalı küçük dinlenme alanı?", answers: ["çadır"], points: 10 },
    { letter: "Ç", question: "sıkıntılı bir durumdan kurtulma yolu?", answers: ["çözüm"], points: 10 },

    { letter: "D", question: "bilgi ve belgelerin saklandığı dosya türü?", answers: ["dosya"], points: 10 },
    { letter: "D", question: "bir şeyin parasal karşılığı?", answers: ["değer"], points: 10 },
    { letter: "D", question: "belli bir zaman aralığı?", answers: ["dönem"], points: 10 },
    { letter: "D", question: "Dünya'nın kendi ekseni etrafındaki hareketi?", answers: ["dönüş"], points: 10 },
    { letter: "D", question: "düzensizliği ortadan kaldıran sistem?", answers: ["düzen"], points: 10 },

    { letter: "E", question: "fırında pişen temel yiyecek?", answers: ["ekmek"], points: 10 },
    { letter: "E", question: "öğrenme ve öğretme süreci?", answers: ["eğitim"], points: 10 },
    { letter: "E", question: "bir taşınmaz mal için kullanılan genel kelime?", answers: ["emlak"], points: 10 },
    { letter: "E", question: "doğa dostu anlamında kullanılan kavram?", answers: ["ekolojik", "eko"], points: 10 },
    { letter: "E", question: "bir işi yapma biçimi veya hareket?", answers: ["eylem"], points: 10 },

    { letter: "F", question: "düşünce veya görüş anlamına gelen kelime?", answers: ["fikir"], points: 10 },
    { letter: "F", question: "madde ve enerjiyi inceleyen bilim?", answers: ["fizik"], points: 10 },
    { letter: "F", question: "alışveriş sonunda verilen belge?", answers: ["fiş", "fatura"], points: 10 },
    { letter: "F", question: "bir spor takımının taraftar topluluğu?", answers: ["fan"], points: 10 },
    { letter: "F", question: "yararlı sonuç veya çıkar?", answers: ["fayda"], points: 10 },

    { letter: "G", question: "bir yere girerken kullanılan bölüm?", answers: ["giriş"], points: 10 },
    { letter: "G", question: "birine inanma duygusu?", answers: ["güven"], points: 10 },
    { letter: "G", question: "gökyüzünde gece görülen ışıklı cisim?", answers: ["göktaşı", "gezegen"], points: 10 },
    { letter: "G", question: "açık ve anlaşılır olmayan şey?", answers: ["gizli"], points: 10 },
    { letter: "G", question: "bir bütünü temsil eden küçük görsel işaret?", answers: ["görsel"], points: 10 },

    { letter: "Ğ", question: "Türkçede sözcük başında çok nadir görülen harf?", answers: ["ğ"], points: 10 },
    { letter: "Ğ", question: "Bu harfle kelime bulmak neden zordur?", answers: ["nadir", "yok"], points: 10 },
    { letter: "Ğ", question: "Türk alfabesinde hangi tür sesi yumuşatır?", answers: ["ünsüz", "sessiz"], points: 10 },
    { letter: "Ğ", question: "Yaygın adı nedir?", answers: ["yumuşakg", "yumuşak g"], points: 10 },
    { letter: "Ğ", question: "Genelde kelimenin neresinde bulunur?", answers: ["ortasında", "sonunda", "orta"], points: 10 },

    { letter: "H", question: "bir olay hakkında verilen bilgi?", answers: ["haber"], points: 10 },
    { letter: "H", question: "yasal kuralları inceleyen alan?", answers: ["hukuk"], points: 10 },
    { letter: "H", question: "rahatlık ve iç ferahlığı?", answers: ["huzur"], points: 10 },
    { letter: "H", question: "ulaşılmak istenen sonuç?", answers: ["hedef"], points: 10 },
    { letter: "H", question: "insanın kurduğu gerçek dışı düşünce?", answers: ["hayal"], points: 10 },

    { letter: "I", question: "akarsudan küçük su yolu?", answers: ["ırmak"], points: 10 },
    { letter: "I", question: "havayı veya yeri aydınlatan enerji?", answers: ["ışık"], points: 10 },
    { letter: "I", question: "temiz olmayan ve kaygan zemin?", answers: ["ıslak"], points: 10 },
    { letter: "I", question: "kuş veya böcek gibi canlıların ses çıkarması?", answers: ["ıslık"], points: 10 },
    { letter: "I", question: "hayvan soyunu anlatan kelime?", answers: ["ırk"], points: 10 },

    { letter: "İ", question: "bir metnin veya konunun ana malzemesi?", answers: ["içerik"], points: 10 },
    { letter: "İ", question: "bir düşünceyi anlatan yazı veya söz?", answers: ["ifade"], points: 10 },
    { letter: "İ", question: "bilgi ve öğrenme anlamında kullanılan eski kelime?", answers: ["ilim"], points: 10 },
    { letter: "İ", question: "bir işe duyulan istek?", answers: ["ilgi"], points: 10 },
    { letter: "İ", question: "insanı harekete geçiren iç ses?", answers: ["istek"], points: 10 },

    { letter: "J", question: "Uzak Doğu'da bir ülke?", answers: ["japonya"], points: 10 },
    { letter: "J", question: "trafikte kullanılan küçük hızlı bot?", answers: ["jet"], points: 10 },
    { letter: "J", question: "haber yazarı veya muhabir?", answers: ["jurnalci", "gazeteci"], points: 10 },
    { letter: "J", question: "müzikte doğaçlamaya açık türün İngilizce adı?", answers: ["jazz"], points: 10 },
    { letter: "J", question: "Fransızcadan geçen gösterişli söz?", answers: ["jest"], points: 10 },

    { letter: "K", question: "çayla birlikte sık tüketilen gevrek yiyecek?", answers: ["kurabiye"], points: 10 },
    { letter: "K", question: "karar vermek için kullanılan ölçüt?", answers: ["kriter"], points: 10 },
    { letter: "K", question: "konuşulan veya incelenen başlık?", answers: ["konu"], points: 10 },
    { letter: "K", question: "yazın serinleten meyve?", answers: ["karpuz"], points: 10 },
    { letter: "K", question: "kapının açılıp kapanmasını sağlayan düzenek?", answers: ["kilit"], points: 10 },

    { letter: "L", question: "ampulde ışık veren araç?", answers: ["lamba"], points: 10 },
    { letter: "L", question: "ekşi tadıyla bilinen sarı meyve?", answers: ["limon"], points: 10 },
    { letter: "L", question: "dil bilimiyle ilgili alan?", answers: ["linguistik", "dilbilim"], points: 10 },
    { letter: "L", question: "bir markayı temsil eden işaret?", answers: ["logo"], points: 10 },
    { letter: "L", question: "misket limonu olarak da bilinen meyve?", answers: ["lime", "limon"], points: 10 },

    { letter: "M", question: "seslerden oluşan sanat?", answers: ["müzik"], points: 10 },
    { letter: "M", question: "iletişim araçlarının genel adı?", answers: ["medya"], points: 10 },
    { letter: "M", question: "bir şeyi ölçmek için kullanılan değer?", answers: ["metre"], points: 10 },
    { letter: "M", question: "doğada bulunan sert madde?", answers: ["metal"], points: 10 },
    { letter: "M", question: "bir işin veya yazının ana anlamı?", answers: ["metin"], points: 10 },

    { letter: "N", question: "bir şeyin sebebini soran kelime?", answers: ["neden"], points: 10 },
    { letter: "N", question: "hoş ve ince anlamına gelen sıfat?", answers: ["nazik"], points: 10 },
    { letter: "N", question: "bir şeyin sayıca az olması?", answers: ["nadir"], points: 10 },
    { letter: "N", question: "insanın soluk alıp verdiği şey?", answers: ["nefes"], points: 10 },
    { letter: "N", question: "bir konudaki amaç veya istek?", answers: ["niyet"], points: 10 },

    { letter: "O", question: "ağaçlarla kaplı geniş alan?", answers: ["orman"], points: 10 },
    { letter: "O", question: "iki veya daha fazla parçanın birleştiği yer?", answers: ["ortak", "orta"], points: 10 },
    { letter: "O", question: "sahnede veya ekranda rol yapan kişi?", answers: ["oyuncu"], points: 10 },
    { letter: "O", question: "bir işi yapma düzeni?", answers: ["organizasyon"], points: 10 },
    { letter: "O", question: "bazı sorularda seçenek anlamında kullanılan kelime?", answers: ["opsiyon"], points: 10 },

    { letter: "Ö", question: "bir konuyu kavramaya yarayan kısa anlatım?", answers: ["özet"], points: 10 },
    { letter: "Ö", question: "başkasına ait olmayan kişisel nitelik?", answers: ["özgün"], points: 10 },
    { letter: "Ö", question: "kişiye yol gösteren tavsiye?", answers: ["öneri"], points: 10 },
    { letter: "Ö", question: "bir şeyi saklayan dış parça?", answers: ["örtü"], points: 10 },
    { letter: "Ö", question: "okuldaki ders anlatan kişi?", answers: ["öğretmen"], points: 10 },

    { letter: "P", question: "sebze ve meyve alınan yer?", answers: ["pazar"], points: 10 },
    { letter: "P", question: "emniyet ve asayiş görevlisi?", answers: ["polis"], points: 10 },
    { letter: "P", question: "yuvarlak ve hamurlu İtalyan yemeği?", answers: ["pizza"], points: 10 },
    { letter: "P", question: "bazı dillerde kalem anlamına gelen kelime?", answers: ["pen"], points: 10 },
    { letter: "P", question: "basınç ölçmede kullanılan birim ailesi?", answers: ["pascal"], points: 10 },

    { letter: "R", question: "ses veya görüntü yayını yapan cihaz?", answers: ["radyo"], points: 10 },
    { letter: "R", question: "otomatik iş yapabilen makine?", answers: ["robot"], points: 10 },
    { letter: "R", question: "spor karşılaşmasında en yüksek başarı?", answers: ["rekor"], points: 10 },
    { letter: "R", question: "düzenli yapılan günlük alışkanlık?", answers: ["rutin"], points: 10 },
    { letter: "R", question: "sahnede veya filmde canlandırılan kişi?", answers: ["rol"], points: 10 },

    { letter: "S", question: "kahvaltıda içilen beyaz içecek?", answers: ["süt"], points: 10 },
    { letter: "S", question: "güne başlanan zaman?", answers: ["sabah"], points: 10 },
    { letter: "S", question: "bir problem hakkında istenen cevap?", answers: ["soru"], points: 10 },
    { letter: "S", question: "güneşle özdeşleşen parlak renk?", answers: ["sarı"], points: 10 },
    { letter: "S", question: "bir metindeki anlamlı kelime dizisi?", answers: ["söz"], points: 10 },

    { letter: "Ş", question: "tatlılarda sık kullanılan beyaz madde?", answers: ["şeker"], points: 10 },
    { letter: "Ş", question: "büyük yerleşim yeri?", answers: ["şehir"], points: 10 },
    { letter: "Ş", question: "gizli bilgiyi koruyan kelime?", answers: ["şifre"], points: 10 },
    { letter: "Ş", question: "müzikte sözlü eser?", answers: ["şarkı"], points: 10 },
    { letter: "Ş", question: "ince ve hoş anlamında kullanılan sıfat?", answers: ["şirin"], points: 10 },

    { letter: "T", question: "geçmiş olayları inceleyen alan?", answers: ["tarih"], points: 10 },
    { letter: "T", question: "bir ekibin birlikte oynadığı oyun grubu?", answers: ["takım"], points: 10 },
    { letter: "T", question: "dinlenme veya gezi amacıyla yapılan ara?", answers: ["tatil"], points: 10 },
    { letter: "T", question: "yemek pişirmede kullanılan geniş kap?", answers: ["tava"], points: 10 },
    { letter: "T", question: "demiryolu üzerinde giden araç?", answers: ["tren"], points: 10 },

    { letter: "U", question: "havada giden ulaşım aracı?", answers: ["uçak"], points: 10 },
    { letter: "U", question: "kişinin dikkatini çeken bildirim?", answers: ["uyarı"], points: 10 },
    { letter: "U", question: "bir şeye elverişli anlamındaki kelime?", answers: ["uygun"], points: 10 },
    { letter: "U", question: "ülkelerin resmî temsilcisi?", answers: ["ulus", "elçi"], points: 10 },
    { letter: "U", question: "bir şeyin parçalarından oluşan bütün?", answers: ["unsur"], points: 10 },

    { letter: "Ü", question: "ülke veya kurum adıyla tanınan yüksek okul?", answers: ["üniversite"], points: 10 },
    { letter: "Ü", question: "bir ülkede kullanılan para karşılığı?", answers: ["ücret"], points: 10 },
    { letter: "Ü", question: "yolun üstünden geçmeyi sağlayan yapı?", answers: ["üstgeçit"], points: 10 },
    { letter: "Ü", question: "bir şeyin en yukarı bölümü?", answers: ["üst"], points: 10 },
    { letter: "Ü", question: "kötü bir olay karşısında hissedilen duygu?", answers: ["üzgün"], points: 10 },

    { letter: "V", question: "denizde yolcu taşıyan araç?", answers: ["vapur"], points: 10 },
    { letter: "V", question: "zamanı ifade eden kısa kelime?", answers: ["vakit"], points: 10 },
    { letter: "V", question: "aşı anlamında kullanılan tıbbi terim?", answers: ["vaksin"], points: 10 },
    { letter: "V", question: "spor veya siyasette söz hakkı?", answers: ["veto"], points: 10 },
    { letter: "V", question: "kişinin ana yurdu?", answers: ["vatan"], points: 10 },

    { letter: "Y", question: "gerçek olmayan söz?", answers: ["yalan"], points: 10 },
    { letter: "Y", question: "üzerinde uyunan eşya?", answers: ["yatak"], points: 10 },
    { letter: "Y", question: "bir metni kaleme alan kişi?", answers: ["yazar"], points: 10 },
    { letter: "Y", question: "gelecekteki gün?", answers: ["yarın"], points: 10 },
    { letter: "Y", question: "bir şeyi yemeye uygun duruma getirme işi?", answers: ["yemek"], points: 10 },

    { letter: "Z", question: "kolay olmayan anlamındaki kelime?", answers: ["zor"], points: 10 },
    { letter: "Z", question: "güçlü kokulu sarımsı baharat?", answers: ["zerdeçal"], points: 10 },
    { letter: "Z", question: "eski metinlerde kitap eki veya ilave anlamında kelime?", answers: ["zeyil"], points: 10 },
    { letter: "Z", question: "istenmeyen kayıp veya hasar?", answers: ["zarar"], points: 10 },
    { letter: "Z", question: "en yüksek nokta anlamında kullanılan kelime?", answers: ["zirve"], points: 10 },
];

