(function initForeheadWords(root, factory) {
    "use strict";

    const data = factory();
    if (typeof module === "object" && module.exports) module.exports = data;
    else root.OmniForeheadWords = data;
})(typeof globalThis !== "undefined" ? globalThis : window, function createForeheadWords() {
    "use strict";

    const split = (value) => value.split("|").map((word) => word.trim()).filter(Boolean);
    const definitions = [
        ["animals", "Hayvanlar", "HY", "Doğadaki canlıları anlat ve tahmin et."],
        ["movies", "Filmler", "FL", "Yerli ve yabancı sinema filmleri."],
        ["series", "Diziler", "DZ", "Ekranın unutulmaz dizi yapımları."],
        ["celebrities", "Ünlüler", "ÜN", "Oyuncular, müzisyenler ve tanınmış isimler."],
        ["professions", "Meslekler", "MS", "İşleri hareketlerle ve ipuçlarıyla anlat."],
        ["sports", "Spor", "SP", "Spor dalları, terimler ve önemli isimler."],
        ["football", "Futbol", "FB", "Futbolcular, kulüpler, kupalar ve terimler."],
        ["foods", "Yemekler", "YM", "Türk ve dünya mutfağından lezzetler."],
        ["cities", "Şehirler", "ŞH", "Türkiye'den ve dünyadan şehirler."],
        ["countries", "Ülkeler", "ÜL", "Dünyanın farklı bölgelerinden ülkeler."],
        ["brands", "Markalar", "MR", "Günlük hayatta karşılaşılan markalar."],
        ["technology", "Teknoloji", "TK", "Dijital dünya, cihazlar ve kavramlar."],
        ["games", "Oyunlar", "OY", "Video, masa ve geleneksel oyunlar."],
        ["objects", "Nesneler", "NS", "Evde, okulda ve sokakta gördüğümüz eşyalar."],
        ["kids", "Çocuk", "ÇC", "Çocuklara uygun eğlenceli karakter ve kavramlar."],
        ["hard", "Zor Kelimeler", "ZK", "Anlatması zor kavramlar ve soyut sözcükler."],
    ];

    const raw = {
        animals: split("Aslan|Kaplan|Leopar|Çita|Jaguar|Puma|Vaşak|Fil|Zürafa|Zebra|Gergedan|Su aygırı|Deve|Lama|Alpaka|At|Eşek|Katır|İnek|Boğa|Manda|Koyun|Keçi|Domuz|Tavşan|Sincap|Kirpi|Köstebek|Fare|Hamster|Kunduz|Su samuru|Rakun|Porsuk|Kokarca|Tilki|Kurt|Çakal|Sırtlan|Ayı|Panda|Koala|Kanguru|Keseli sıçan|Maymun|Goril|Şempanze|Orangutan|Lemur|Tembel hayvan|Geyik|Karaca|Ceylan|Antilop|Bizon|Gnu|Yaban domuzu|Kutup ayısı|Penguen|Devekuşu|Flamingo|Pelikan|Leylek|Kartal|Şahin|Doğan|Baykuş|Papağan|Kanarya|Serçe|Karga|Güvercin|Tavus kuşu|Kuğu|Ördek|Kaz|Hindi|Horoz|Tavuk|Bıldırcın|Balina|Yunus|Köpek balığı|Vatoz|Ahtapot|Kalamar|Denizanası|Denizatı|Yengeç|Istakoz|Kaplumbağa|Timsah|Kertenkele|İguana|Bukalemun|Yılan|Kurbağa|Semender|Kelebek|Arı"),
        movies: split("Hababam Sınıfı|Tosun Paşa|Süt Kardeşler|Neşeli Günler|G.O.R.A.|A.R.O.G.|Vizontele|Babam ve Oğlum|Eşkıya|Kış Uykusu|Bir Zamanlar Anadolu'da|Selvi Boylum Al Yazmalım|Yol|Kelebeğin Rüyası|Organize İşler|Yahşi Batı|Ayla|7. Koğuştaki Mucize|Dağ 2|Nefes Vatan Sağolsun|Matrix|Titanic|Avatar|Gladyatör|Başlangıç|Yıldızlararası|Dövüş Kulübü|Esaretin Bedeli|Baba|Kara Şövalye|Forrest Gump|Yeşil Yol|Truman Show|Prestij|Akıl Oyunları|Er Ryan'ı Kurtarmak|Kuzuların Sessizliği|Ucuz Roman|Geleceğe Dönüş|Jurassic Park|Jaws|Rocky|Rambo|Terminatör|Alien|Predator|Hayalet Avcıları|Evde Tek Başına|Maske|Ace Ventura|Karayip Korsanları|Yüzüklerin Efendisi|Hobbit|Harry Potter ve Felsefe Taşı|Star Wars|Indiana Jones|Görevimiz Tehlike|Hızlı ve Öfkeli|John Wick|Top Gun|Mad Max|Blade Runner|Dune|Oppenheimer|Barbie|La La Land|Whiplash|Parazit|Joker|Bohemian Rhapsody|Sosyal Ağ|Zindan Adası|Sıkıysa Yakala|Büyük Balık|Sevginin Gücü|Can Dostum|Umudunu Kaybetme|Dokunulmazlar|Pi'nin Yaşamı|Slumdog Milyoner|Amelie|Leon|Rezervuar Köpekleri|Büyük Lebowski|Fargo|Otomatik Portakal|2001 Uzay Yolu Macerası|Sapık|Arka Pencere|Vertigo|Kazablanka|Rüzgar Gibi Geçti|Oz Büyücüsü|Singin' in the Rain|Schindler'in Listesi|Apollo 13|Marslı|Gravity|Coco|Yukarı Bak"),
        series: split("Avrupa Yakası|Leyla ile Mecnun|Ezel|Kurtlar Vadisi|Aşk-ı Memnu|Behzat Ç.|Şahsiyet|Bir Başkadır|Masum|İçerde|Çukur|Kardeş Payı|İşler Güçler|Yalan Dünya|Geniş Aile|Seksenler|Tatlı Hayat|Süper Baba|İkinci Bahar|Yaprak Dökümü|Breaking Bad|Game of Thrones|Friends|The Office|Sherlock|Dark|Stranger Things|Lost|Prison Break|The Walking Dead|Black Mirror|Peaky Blinders|Narcos|Vikings|The Crown|House of the Dragon|Better Call Saul|Succession|The Last of Us|Wednesday|Squid Game|La Casa de Papel|Lupin|The Boys|Westworld|The Mandalorian|Andor|House|Dexter|Mentalist|How I Met Your Mother|Modern Family|Brooklyn Nine-Nine|Seinfeld|The Big Bang Theory|Community|Ted Lasso|Fleabag|After Life|The Bear|Shameless|Ozark|Mindhunter|True Detective|Fariña|Mr. Robot|Hannibal|Suits|Mad Men|Boardwalk Empire|The Wire|Sopranos|Band of Brothers|Chernobyl|Fargo Dizisi|The Queen's Gambit|Anne with an E|Gilmore Girls|Gossip Girl|Elite|Euphoria|Sex Education|Bridgerton|Outlander|Doctor Who|Star Trek|The X-Files|Fringe|Supernatural|Lucifer|Smallville|Arrow|Daredevil|Punisher|Jessica Jones|The Umbrella Academy|One Piece Dizisi|Avatar Son Hava Bükücü|Rick and Morty|BoJack Horseman|Arcane"),
        celebrities: split("Kemal Sunal|Şener Şen|Adile Naşit|Münir Özkul|Tarık Akan|Türkan Şoray|Kadir İnanır|Hülya Koçyiğit|Cüneyt Arkın|Filiz Akın|Yılmaz Güney|Haluk Bilginer|Demet Akbağ|Cem Yılmaz|Ata Demirer|Yılmaz Erdoğan|Gülse Birsel|Engin Günaydın|Binnur Kaya|Ezgi Mola|Tarkan|Sezen Aksu|Barış Manço|Cem Karaca|Ajda Pekkan|Zeki Müren|Müslüm Gürses|Neşet Ertaş|Orhan Gencebay|Sertab Erener|Kenan Doğulu|Teoman|Şebnem Ferah|Mabel Matiz|Sıla Gençoğlu|Hadise|Edis Görgülü|Gökhan Türkmen|Ceza|Sagopa Kajmer|Leonardo DiCaprio|Brad Pitt|Tom Hanks|Johnny Depp|Keanu Reeves|Robert De Niro|Al Pacino|Morgan Freeman|Denzel Washington|Will Smith|Tom Cruise|Matt Damon|Christian Bale|Joaquin Phoenix|Ryan Gosling|Hugh Jackman|Jim Carrey|Eddie Murphy|Jackie Chan|Dwayne Johnson|Meryl Streep|Julia Roberts|Sandra Bullock|Nicole Kidman|Cate Blanchett|Natalie Portman|Scarlett Johansson|Emma Stone|Jennifer Lawrence|Anne Hathaway|Angelina Jolie|Charlize Theron|Audrey Hepburn|Marilyn Monroe|Charlie Chaplin|Alfred Hitchcock|Steven Spielberg|Christopher Nolan|Quentin Tarantino|Martin Scorsese|Taylor Swift|Beyoncé|Rihanna|Adele|Lady Gaga|Madonna|Britney Spears|Michael Jackson|Elvis Presley|Freddie Mercury|David Bowie|Elton John|Ed Sheeran|Bruno Mars|Eminem|Snoop Dogg|Billie Eilish|Shakira|Jennifer Lopez|Celine Dion"),
        professions: split("Doktor|Hemşire|Diş hekimi|Eczacı|Veteriner|Psikolog|Diyetisyen|Fizyoterapist|Paramedik|Cerrah|Öğretmen|Akademisyen|Rehber öğretmen|Okul müdürü|Kütüphaneci|Anaokulu öğretmeni|Mühendis|Mimar|İç mimar|Şehir plancısı|Yazılım geliştirici|Veri bilimci|Siber güvenlik uzmanı|Sistem yöneticisi|Teknisyen|Elektrikçi|Tesisatçı|Marangoz|Kaynakçı|Oto tamircisi|Aşçı|Pastacı|Garson|Barista|Kasap|Fırıncı|Çiftçi|Bahçıvan|Balıkçı|Arıcı|Avukat|Hakim|Savcı|Noter|Arabulucu|Polis|İtfaiyeci|Asker|Zabıta|Güvenlik görevlisi|Pilot|Kabin memuru|Makinist|Kaptan|Şoför|Kurye|Postacı|Taksi şoförü|Otobüs şoförü|Tren makinisti|Muhasebeci|Bankacı|Sigortacı|Emlak danışmanı|İnsan kaynakları uzmanı|Pazarlamacı|Satış temsilcisi|Ekonomist|Mali müşavir|Girişimci|Gazeteci|Muhabir|Editör|Yazar|Çevirmen|Fotoğrafçı|Kameraman|Sunucu|Spiker|Radyocu|Oyuncu|Yönetmen|Senarist|Yapımcı|Müzisyen|Şarkıcı|Dansçı|Ressam|Heykeltıraş|Grafik tasarımcı|Moda tasarımcısı|Terzi|Kuaför|Berber|Makyaj sanatçısı|Spor antrenörü|Cankurtaran|Turist rehberi|Arkeolog|Astronot"),
        sports: split("Basketbol|Voleybol|Tenis|Masa tenisi|Badminton|Hentbol|Beyzbol|Softbol|Ragbi|Amerikan futbolu|Buz hokeyi|Çim hokeyi|Su topu|Yüzme|Dalış|Senkronize yüzme|Kürek|Kano|Yelken|Sörf|Rüzgar sörfü|Atletizm|Maraton|Sprint|Engelli koşu|Yüksek atlama|Sırıkla atlama|Uzun atlama|Üç adım atlama|Cirit atma|Disk atma|Gülle atma|Bisiklet|Dağ bisikleti|Triatlon|Jimnastik|Ritmik jimnastik|Trambolin|Halter|Vücut geliştirme|Boks|Kick boks|Muay Thai|Karate|Judo|Tekvando|Güreş|Eskrim|Okçuluk|Atıcılık|Binicilik|Kayak|Snowboard|Buz pateni|Kızak|Curling|Dağcılık|Kaya tırmanışı|Oryantiring|Kaykay|Paten|Golf|Bowling|Bilardo|Dart|Satranç sporu|Formula 1|Ralli|MotoGP|Motokros|Karting|Smaç|Turnike|Ribaund|Üçlük|Servis atışı|Ace|Tie-break|Grand Slam|Pota|File|Raket|Kronometre|Madalya|Podyum|Bayrak yarışı|Foto finiş|Dünya rekoru|Olimpiyat meşalesi|Paralimpik oyunlar|Fair play|Doping kontrolü|Spor salonu|Isınma hareketi|Kondisyon|Antrenman kampı|Hakem düdüğü|Nakavt|Raunt|Kulvar"),
        football: split("Cristiano Ronaldo|Lionel Messi|Neymar|Kylian Mbappé|Erling Haaland|Mohamed Salah|Kevin De Bruyne|Luka Modrić|Karim Benzema|Robert Lewandowski|Zinedine Zidane|Ronaldinho|Ronaldo Nazário|David Beckham|Thierry Henry|Andrés Iniesta|Xavi Hernández|Sergio Ramos|Manuel Neuer|Gianluigi Buffon|Arda Güler|Hakan Çalhanoğlu|Kenan Yıldız|Nihat Kahveci|Rüştü Reçber|Lefter Küçükandonyadis|Metin Oktay|Alex de Souza|Gheorghe Hagi|Didier Drogba|Galatasaray|Fenerbahçe|Beşiktaş|Trabzonspor|Başakşehir|Bursaspor|Real Madrid|Barcelona|Manchester United|Manchester City|Liverpool|Arsenal|Chelsea|Bayern Münih|Borussia Dortmund|Paris Saint-Germain|Juventus|Milan|Inter|Napoli|Ajax|Benfica|Porto|Celtic|Boca Juniors|River Plate|Şampiyonlar Ligi|Avrupa Ligi|Konferans Ligi|Dünya Kupası|Avrupa Şampiyonası|Copa América|Ballon d'Or|Süper Lig|Premier Lig|La Liga|Bundesliga|Serie A|Ligue 1|Ofsayt|Penaltı|Korner|Serbest vuruş|Taç atışı|Sarı kart|Kırmızı kart|VAR|Uzatma dakikası|Röveşata|Vole|Kafa golü|Hat-trick|Asist|Kontra atak|Pres|Çalım|Dripling|Kaleci|Stoper|Bek oyuncusu|Orta saha|Kanat oyuncusu|Santrfor|Teknik direktör|Kaptanlık pazubendi|Transfer dönemi|Derbi|Deplasman|Gol sevinci|Penaltı atışları"),
        foods: split("Adana kebap|Urfa kebap|İskender kebap|Cağ kebabı|Patlıcan kebabı|Döner|Lahmacun|Pide|Mantı|İçli köfte|Çiğ köfte|Mercimek çorbası|Ezogelin çorbası|Tarhana çorbası|Yayla çorbası|Kuru fasulye|Nohut yemeği|Pilav|Bulgur pilavı|Karnıyarık|İmam bayıldı|Musakka|Zeytinyağlı sarma|Biber dolması|Hünkar beğendi|Ali nazik|Tas kebabı|Etli ekmek|Gözleme|Menemen|Kuymak|Kısır|Mercimek köftesi|Su böreği|Sigara böreği|Paçanga böreği|Boyoz|Simit|Bazlama|Katmer|Baklava|Künefe|Sütlaç|Kazandibi|Tavukgöğsü|Revani|Şekerpare|Lokma|Aşure|Helva|Dondurma|Profiterol|Tiramisu|Cheesecake|Brownie|Kurabiye|Çikolatalı pasta|Pizza|Hamburger|Hot dog|Taco|Burrito|Nachos|Sushi|Ramen|Tempura|Pad Thai|Köri|Falafel|Humus|Paella|Risotto|Lazanya|Spagetti|Ravioli|Gnocchi|Kruvasan|Baget ekmek|Soğan çorbası|Sezar salata|Yunan salatası|Patates kızartması|Soğan halkası|Tavuk kanadı|Balık ekmek|Hamsi tava|Midye dolma|Karides güveç|Kalamar tava|Omlet|Pankek|Waffle|Granola|Yoğurt|Ayran|Türk kahvesi|Salep|Boza|Limonata|Komposto"),
        cities: split("İstanbul|Ankara|İzmir|Bursa|Antalya|Adana|Konya|Gaziantep|Şanlıurfa|Mersin|Diyarbakır|Kayseri|Samsun|Eskişehir|Denizli|Trabzon|Erzurum|Van|Malatya|Sivas|Mardin|Çanakkale|Muğla|Aydın|Balıkesir|Tekirdağ|Edirne|Kars|Rize|Hatay|Paris|Londra|Roma|Berlin|Madrid|Barselona|Lizbon|Amsterdam|Brüksel|Viyana|Prag|Budapeşte|Atina|Sofya|Bükreş|Varşova|Kopenhag|Stockholm|Oslo|Helsinki|Dublin|Edinburgh|Zürih|Cenevre|Venedik|Milano|Napoli|Floransa|Münih|Hamburg|New York|Los Angeles|Chicago|Miami|San Francisco|Washington|Boston|Toronto|Vancouver|Montreal|Mexico City|Rio de Janeiro|São Paulo|Buenos Aires|Santiago|Lima|Bogota|Tokyo|Kyoto|Seul|Pekin|Şanghay|Hong Kong|Bangkok|Singapur|Kuala Lumpur|Cakarta|Mumbai|Yeni Delhi|Dubai|Abu Dabi|Doha|Kahire|Kazablanka Şehri|Cape Town|Johannesburg|Nairobi|Sidney|Melbourne|Auckland"),
        countries: split("Türkiye|Almanya|Fransa|İtalya|İspanya|Portekiz|Birleşik Krallık|İrlanda|Belçika|Hollanda|Lüksemburg|İsviçre|Avusturya|Danimarka|Norveç|İsveç|Finlandiya|İzlanda|Polonya|Çekya|Slovakya|Macaristan|Romanya|Bulgaristan|Yunanistan|Arnavutluk|Hırvatistan|Slovenya|Sırbistan|Bosna Hersek|Karadağ|Kuzey Makedonya|Ukrayna|Moldova|Gürcistan|Ermenistan|Azerbaycan|Rusya|Amerika Birleşik Devletleri|Kanada|Meksika|Küba|Jamaika|Kosta Rika|Panama|Brezilya|Arjantin|Şili|Peru|Kolombiya|Venezuela|Uruguay|Paraguay|Bolivya|Ekvador|Japonya|Çin|Güney Kore|Kuzey Kore|Moğolistan|Hindistan|Pakistan|Bangladeş|Nepal|Bhutan|Sri Lanka|Tayland|Vietnam|Kamboçya|Laos|Malezya|Endonezya|Filipinler|Singapur Ülkesi|Avustralya|Yeni Zelanda|Fiji|Mısır|Fas|Cezayir|Tunus|Libya|Sudan|Etiyopya|Kenya|Tanzanya|Uganda|Gana|Nijerya|Senegal|Güney Afrika|Madagaskar|Suudi Arabistan|Birleşik Arap Emirlikleri|Katar|Kuveyt|Ürdün|Lübnan|İsrail|İran"),
        brands: split("Apple|Samsung|Sony|LG|Huawei|Xiaomi|Nokia|Motorola|Lenovo|Asus|Acer|Dell|HP|Microsoft|Google|Amazon|Meta|Netflix|Spotify|YouTube|Adobe|Intel|AMD|Nvidia|Canon|Nikon|GoPro|DJI|Tesla|Toyota|Honda|BMW|Mercedes-Benz|Audi|Volkswagen|Volvo|Ford|Renault|Peugeot|Citroën|Fiat|Hyundai|Kia|Porsche|Ferrari|Lamborghini|Bentley|Jeep|Land Rover|Nike|Adidas|Puma Sports|Reebok|New Balance|Under Armour|Converse|Vans|Levi's|Zara|H&M|Mango|Gucci|Prada|Chanel|Dior|Louis Vuitton|Rolex|Swatch|IKEA|Lego|Mattel|Hasbro|Coca-Cola|Pepsi|Fanta|Sprite|Red Bull|Nescafé|Starbucks|McDonald's|Burger King|KFC|Domino's|Subway|Nutella|Ülker|Eti|Pınar|Sütaş|Arçelik|Beko|Vestel|Turkcell|Türk Telekom|Vodafone|Trendyol|Hepsiburada|Migros|CarrefourSA|THY"),
        technology: split("Akıllı telefon|Tablet bilgisayar|Dizüstü bilgisayar|Masaüstü bilgisayar|Akıllı saat|Kablosuz kulaklık|Sanal gerçeklik gözlüğü|Oyun konsolu|E-kitap okuyucu|Aksiyon kamerası|Drone cihazı|3D yazıcı|Robot süpürge|Akıllı televizyon|Projeksiyon cihazı|Modem|Yönlendirici|Ethernet kablosu|USB bellek|Hafıza kartı|Harici disk|SSD|İşlemci|Ekran kartı|Anakart|RAM|Güç kaynağı|Soğutma fanı|Mekanik klavye|Dokunmatik yüzey|Web kamerası|Mikrofon|Hoparlör|Yazıcı|Tarayıcı cihazı|İşletim sistemi|Web tarayıcısı|Mobil uygulama|Bulut depolama|Yapay zeka|Makine öğrenmesi|Derin öğrenme|Büyük veri|Algoritma|Kaynak kodu|Programlama dili|Veritabanı|Sunucu|Veri merkezi|Siber güvenlik|Güvenlik duvarı|Antivirüs|Şifreleme|İki aşamalı doğrulama|Parola yöneticisi|VPN|Wi-Fi|Bluetooth|NFC|GPS|5G|Fiber internet|Uydu interneti|QR kod|Barkod|Biyometrik doğrulama|Yüz tanıma|Parmak izi okuyucu|Dokunmatik ekran|Piksel|Çözünürlük|Yenileme hızı|Batarya|Hızlı şarj|Kablosuz şarj|Güneş paneli|Elektrikli otomobil|Otonom araç|Akıllı ev|Nesnelerin interneti|Blok zinciri|Kripto para|Dijital cüzdan|Sosyal medya|E-posta|Podcast|Canlı yayın|Video konferans|Artırılmış gerçeklik|Metaverse|Kuantum bilgisayar|Nanoteknoloji|Biyoteknoloji|Uydu|Roket teknolojisi|Sensör|Jiroskop|İvmeölçer|Wake Lock|Açık kaynak"),
        games: split("Minecraft|Fortnite|Grand Theft Auto V|Red Dead Redemption 2|The Witcher 3|Cyberpunk 2077|God of War|The Last of Us|Uncharted|Horizon Zero Dawn|Ghost of Tsushima|Elden Ring|Dark Souls|Sekiro|Bloodborne|Skyrim|Fallout|Assassin's Creed|Far Cry|Watch Dogs|Call of Duty|Battlefield|Counter-Strike 2|Valorant|Overwatch|Apex Legends|PUBG|League of Legends|Dota 2|World of Warcraft|Diablo|StarCraft|Civilization|Age of Empires|The Sims|SimCity|Cities Skylines|Football Manager|FIFA Oyunu|eFootball|NBA 2K|Rocket League|Need for Speed|Forza Horizon|Gran Turismo|Mario Kart|Super Mario Bros.|The Legend of Zelda|Pokémon|Animal Crossing|Sonic the Hedgehog|Kirby|Donkey Kong|Metroid|Tetris|Pac-Man|Space Invaders|Street Fighter|Mortal Kombat|Tekken|Resident Evil|Silent Hill|Metal Gear Solid|Death Stranding|Portal|Half-Life|Baldur's Gate|Mass Effect|Dragon Age|Final Fantasy|Persona|Monster Hunter|Genshin Impact|Among Us|Fall Guys|Roblox|Clash of Clans|Candy Crush|Subway Surfers|Angry Birds|Monopoly|Scrabble|Tabu Oyunu|Jenga|Uno|Risk|Catan|Carcassonne|Dixit|Mangala|Tavla|Dama|Okey|İskambil|Saklambaç|Körebe|İstop|Mendil kapmaca|Seksek|Yakan top"),
        objects: split("Telefon|Anahtar|Cüzdan|Çanta|Şemsiye|Kol saati|Gözlük|Ayna|Tarak|Diş fırçası|Havlu|Yastık|Battaniye|Çarşaf|Perde|Halı|Koltuk|Sandalye|Masa|Sehpa|Kitaplık|Elbise dolabı|Askı|Kapı|Pencere|Merdiven|Asansör|Ampul|Abajur|Priz|Uzatma kablosu|Buzdolabı|Fırın|Ocak|Bulaşık makinesi|Çamaşır makinesi|Ütü|Elektrikli süpürge|Tencere|Tava|Çaydanlık|Kettle|Tabak|Kase|Bardak|Kupa|Çatal|Kaşık|Bıçak|Kesme tahtası|Peçete|Saklama kabı|Çöp kutusu|Sünger|Sabunluk|Kova|Paspas|Mandal|Dikiş iğnesi|Makas|Cetvel|Kalem|Silgi|Kalemtıraş|Defter|Kitap|Dosya klasörü|Zımba|Ataç|Yapıştırıcı|Bant|Zarf|Mühür|Büyüteç|Dürbün|Fener|Pusula|Harita|Bavul|Kask|Eldiven|Ayakkabı|Terlik|Kemer|Şapka|Atkı|Yağmurluk|Su şişesi|Termos|Sepet|Oyuncak bebek|Uçurtma|Balon|Mum|Kibrit|Çekiç|Tornavida|Pense|Matkap|Merdivenli tabure"),
        kids: split("Kırmızı Başlıklı Kız|Pamuk Prenses|Yedi Cüceler|Külkedisi|Uyuyan Güzel|Rapunzel|Pinokyo|Peter Pan|Kaptan Kanca|Alice Harikalar Diyarında|Çizmeli Kedi|Hansel ve Gretel|Çirkin Ördek Yavrusu|Kurbağa Prens|Keloğlan|Nasreddin Hoca|Karagöz ve Hacivat|Dede Korkut|Aladdin|Sihirli Lamba|Deniz Kızı|Uçan Halı|Sihirli Değnek|Peri Tozu|Gökkuşağı|Unicorn|Ejderha|Dinozor|Korsan Gemisi|Hazine Sandığı|Uzay Gemisi|Uçan Daire|Ay Gezgini|Oyuncak Robot|Peluş Ayıcık|Tahta At|Yapboz|Boyama Kitabı|Oyun Hamuru|Parmak Boyası|Misket|Topaç|Baloncuk|Su Tabancası|Kumdan Kale|Kaydırak|Salıncak|Tahterevalli|Dönme Dolap|Atlıkarınca|Trambolin|Lunapark|Sirk Çadırı|Palyaço|Sihirbaz|Kukla|Gölge Oyunu|Masal Kitabı|Ninni|Tekerleme|Bilmece|Doğum Günü Pastası|Parti Şapkası|Hediye Paketi|Şeker Sepeti|Pamuk Şeker|Renkli Dondurma|Meyve Suyu|Beslenme Çantası|Okul Servisi|Teneffüs|Tahta Kalemi|Sınıf Başkanı|Karne|Altın Yıldız|Beden Eğitimi|Resim Dersi|Müzik Dersi|Bilim Deneyi|Mıknatıs|Büyüyen Fasulye|Kelebek Kozası|Karınca Yuvası|Kuş Evi|Akvaryum|Çiftlik Evi|Ağaç Ev|Kardan Adam|Kartopu|Yağmur Botu|Güneş Gözlüğü|Plaj Kovası|Deniz Simidi|Bisiklet Zili|Paten Dizlikleri|Uçan Balon|Gizli Kulüp|Arkadaşlık Bilekliği|Dilek Ağacı|Yıldızlı Gece"),
        hard: split("Paradoks|İkilem|Önyargı|Empati|Sezgi|Bilinçaltı|Öz farkındalık|İrade|Vicdan|Kanaat|Varsayım|Çıkarım|Nedensellik|Görelilik|Belirsizlik|Olasılık|Tesadüf|Kader|İroni|Mizah|Hiciv|Mecaz|İmge|Metafor|Analoji|Soyutlama|Genelleme|İstisna|Çelişki|Tutarlılık|Şeffaflık|Tarafsızlık|Uzlaşma|Müzakere|Diplomasi|Egemenlik|Bürokrasi|Hiyerarşi|Liyakat|Meşruiyet|Sürdürülebilirlik|Küreselleşme|Kentleşme|Göçebe yaşam|Kültürel miras|Toplumsal hafıza|Kolektif bilinç|Kamuoyu|Etik değer|Ahlaki sorumluluk|Özgür irade|İfade özgürlüğü|Fırsat eşitliği|Adalet duygusu|Dayanışma|Hoşgörü|Aidiyet|Yabancılaşma|Yalnızlık|Nostalji|Melankoli|Coşku|Kaygı|Çekingenlik|Kararlılık|Azim|Merak|Hayal gücü|Yaratıcılık|İlham|Dönüşüm|Değişim|Gelişim|Uyum|Denge|Kaos|Düzen|Sonsuzluk|Zaman algısı|Mekân algısı|Boyut|Yerçekimi|Enerji dönüşümü|Ekosistem|Biyoçeşitlilik|Evrim|Doğal seçilim|Fotosentez|Kuantum|Kara delik|Işık yılı|Gökada|Atmosfer basıncı|Jeotermal enerji|Elektromanyetizma|Yapay seçilim|Kriptografi|Demografi|Epistemoloji|Varoluşçuluk"),
    };

    const seen = new Set();
    const categories = definitions.map(([id, label, mark, description]) => {
        const words = raw[id].filter((word) => {
            const key = word.toLocaleLowerCase("tr-TR").replace(/\s+/g, " ");
            if (seen.has(key)) return false;
            seen.add(key);
            return true;
        });
        return Object.freeze({ id, label, mark, description, words: Object.freeze(words) });
    });
    const allWords = Object.freeze(categories.flatMap((category) => category.words));
    const mixed = Object.freeze({
        id: "mixed",
        label: "Karışık",
        mark: "KR",
        description: "Tüm kategorilerden sürpriz kelimeler.",
        words: allWords,
    });
    const list = Object.freeze([mixed, ...categories]);
    const byId = Object.freeze(Object.fromEntries(list.map((category) => [category.id, category])));

    return Object.freeze({ categories: list, byId, total: allWords.length });
});
