(function initTabuCards(root, factory) {
    "use strict";

    const cards = factory();

    if (typeof module === "object" && module.exports) {
        module.exports = cards;
    } else {
        root.OmniTabuCards = cards;
    }
})(typeof globalThis !== "undefined" ? globalThis : window, function createTabuCards() {
    "use strict";

    const rows = [
        ["Telefon", "arama|mesaj|cep|numara|konuşmak", "Günlük Yaşam"],
        ["Anahtar", "kapı|kilit|açmak|metal|kaybetmek", "Günlük Yaşam"],
        ["Ayna", "yansıma|bakmak|cam|görüntü|duvar", "Günlük Yaşam"],
        ["Çanta", "taşımak|omuz|eşya|fermuar|kadın", "Günlük Yaşam"],
        ["Şemsiye", "yağmur|ıslanmak|açmak|sap|korumak", "Günlük Yaşam"],
        ["Saat", "zaman|kol|dakika|akrep|yelkovan", "Günlük Yaşam"],
        ["Gözlük", "görmek|cam|çerçeve|göz|numara", "Günlük Yaşam"],
        ["Cüzdan", "para|kart|cep|kimlik|deri", "Günlük Yaşam"],
        ["Kapı", "açmak|kapatmak|kol|ev|giriş", "Günlük Yaşam"],
        ["Pencere", "cam|perde|açmak|hava|manzara", "Günlük Yaşam"],
        ["Koltuk", "oturmak|salon|rahat|kanepe|mobilya", "Günlük Yaşam"],
        ["Masa", "sandalye|yemek|çalışmak|ayak|mobilya", "Günlük Yaşam"],
        ["Sandalye", "oturmak|masa|ayak|sırt|mobilya", "Günlük Yaşam"],
        ["Yastık", "uyumak|baş|yatak|yumuşak|kılıf", "Günlük Yaşam"],
        ["Battaniye", "örtmek|sıcak|yatak|kış|yün", "Günlük Yaşam"],
        ["Buzdolabı", "soğuk|mutfak|yiyecek|kapı|dondurucu", "Günlük Yaşam"],
        ["Çamaşır Makinesi", "yıkamak|deterjan|kıyafet|tambur|sıkmak", "Günlük Yaşam"],
        ["Ütü", "kırışık|kıyafet|sıcak|buhar|masa", "Günlük Yaşam"],
        ["Süpürge", "temizlik|toz|yer|elektrik|çekmek", "Günlük Yaşam"],
        ["Fırça", "saç|diş|boya|kıl|taramak", "Günlük Yaşam"],
        ["Sabun", "el|yıkamak|köpük|temizlik|banyo", "Günlük Yaşam"],
        ["Havlu", "kurulamak|banyo|ıslak|kumaş|plaj", "Günlük Yaşam"],
        ["Merdiven", "basamak|çıkmak|inmek|kat|korkuluk", "Günlük Yaşam"],
        ["Asansör", "kat|düğme|çıkmak|kabin|bina", "Günlük Yaşam"],
        ["Balkon", "ev|dışarı|manzara|kapı|çiçek", "Günlük Yaşam"],

        ["Bilgisayar", "ekran|klavye|fare|internet|işlemci", "Teknoloji"],
        ["İnternet", "bağlantı|site|ağ|çevrim içi|modem", "Teknoloji"],
        ["Klavye", "tuş|yazmak|bilgisayar|harf|boşluk", "Teknoloji"],
        ["Fare", "tıklamak|imleç|bilgisayar|kablosuz|tuş", "Teknoloji"],
        ["Ekran", "görüntü|monitör|piksel|bakmak|parlaklık", "Teknoloji"],
        ["Yazıcı", "kağıt|mürekkep|baskı|çıktı|tarayıcı", "Teknoloji"],
        ["Kamera", "fotoğraf|video|çekmek|lens|görüntü", "Teknoloji"],
        ["Robot", "makine|insan|otomatik|yapay|metal", "Teknoloji"],
        ["Yapay Zeka", "algoritma|öğrenmek|robot|veri|ChatGPT", "Teknoloji"],
        ["Şifre", "gizli|giriş|hesap|harf|güvenlik", "Teknoloji"],
        ["Uygulama", "telefon|indirmek|program|mağaza|kullanmak", "Teknoloji"],
        ["Sosyal Medya", "paylaşım|takipçi|beğeni|internet|profil", "Teknoloji"],
        ["E-posta", "mesaj|göndermek|gelen kutusu|adres|ek", "Teknoloji"],
        ["Wi-Fi", "kablosuz|internet|şifre|modem|bağlanmak", "Teknoloji"],
        ["Bluetooth", "kablosuz|kulaklık|bağlantı|yakın|mavi", "Teknoloji"],
        ["Kulaklık", "müzik|kulak|ses|takmak|kablosuz", "Teknoloji"],
        ["Mikrofon", "ses|konuşmak|kayıt|şarkı|sahne", "Teknoloji"],
        ["Pil", "enerji|şarj|artı|eksi|bitmek", "Teknoloji"],
        ["Şarj Aleti", "telefon|pil|kablo|priz|doldurmak", "Teknoloji"],
        ["Yazılım", "program|kod|bilgisayar|geliştirici|güncelleme", "Teknoloji"],
        ["Virüs", "bilgisayar|zararlı|bulaşmak|antivirüs|dosya", "Teknoloji"],
        ["Çevrim İçi Depolama", "bulut|internet|dosya|sunucu|yedek", "Teknoloji"],
        ["Oyun Konsolu", "oynamak|kumanda|ekran|PlayStation|Xbox", "Teknoloji"],
        ["Akıllı Saat", "kol|bildirim|adım|telefon|ekran", "Teknoloji"],
        ["Drone", "uçmak|kamera|uzaktan|pervane|hava", "Teknoloji"],

        ["Futbol", "top|gol|saha|takım|ayak", "Spor"],
        ["Basketbol", "pota|top|smaç|saha|beş", "Spor"],
        ["Voleybol", "file|top|servis|smaç|altı", "Spor"],
        ["Tenis", "raket|top|kort|servis|set", "Spor"],
        ["Yüzme", "havuz|su|kulaç|mayo|yüzücü", "Spor"],
        ["Koşu", "hız|ayak|parkur|yarış|nefes", "Spor"],
        ["Bisiklet", "pedal|tekerlek|gidon|sürmek|kask", "Spor"],
        ["Kayak", "kar|dağ|kış|baton|pist", "Spor"],
        ["Boks", "ring|eldiven|yumruk|nakavt|raunt", "Spor"],
        ["Güreş", "minder|pehlivan|tutmak|yağlı|rakip", "Spor"],
        ["Hakem", "düdük|karar|maç|kart|kural", "Spor"],
        ["Kaleci", "kale|top|eldiven|gol|kurtarmak", "Spor"],
        ["Gol", "kale|top|atmak|skor|sevinç", "Spor"],
        ["Penaltı", "on bir metre|kaleci|faul|vuruş|ceza", "Spor"],
        ["Stadyum", "tribün|taraftar|maç|saha|kalabalık", "Spor"],
        ["Forma", "takım|giymek|numara|renk|oyuncu", "Spor"],
        ["Madalya", "altın|ödül|boyun|yarış|kazanmak", "Spor"],
        ["Olimpiyat", "spor|ülke|madalya|dört yıl|oyunlar", "Spor"],
        ["Antrenör", "takım|çalıştırmak|sporcu|taktik|hoca", "Spor"],
        ["Maraton", "koşmak|uzun|kilometre|yarış|dayanıklılık", "Spor"],
        ["Jimnastik", "esnek|hareket|denge|spor|minder", "Spor"],
        ["Masa Tenisi", "pinpon|raket|file|top|masa", "Spor"],
        ["Okçuluk", "yay|ok|hedef|nişan|atmak", "Spor"],
        ["Sörf", "dalga|tahta|deniz|denge|sahil", "Spor"],
        ["Dalış", "su|deniz|tüp|maske|derin", "Spor"],

        ["Okul", "öğrenci|öğretmen|ders|sınıf|eğitim", "Okul"],
        ["Öğretmen", "ders|öğrenci|anlatmak|okul|sınıf", "Okul"],
        ["Öğrenci", "okul|ders|sınav|öğrenmek|öğretmen", "Okul"],
        ["Sınav", "soru|cevap|not|çalışmak|süre", "Okul"],
        ["Ödev", "ev|ders|yapmak|öğretmen|teslim", "Okul"],
        ["Kitap", "okumak|sayfa|yazar|kapak|roman", "Okul"],
        ["Defter", "yazmak|sayfa|çizgi|kalem|ders", "Okul"],
        ["Kalem", "yazmak|silgi|uç|mürekkep|defter", "Okul"],
        ["Tahta", "yazmak|sınıf|öğretmen|silmek|tebeşir", "Okul"],
        ["Sınıf", "öğrenci|ders|okul|masa|öğretmen", "Okul"],
        ["Üniversite", "fakülte|kampüs|öğrenci|bölüm|diploma", "Okul"],
        ["Diploma", "mezuniyet|belge|okul|başarı|tören", "Okul"],
        ["Kütüphane", "kitap|sessiz|okumak|raf|ödünç", "Okul"],
        ["Laboratuvar", "deney|bilim|önlük|tüp|araştırma", "Okul"],
        ["Matematik", "sayı|işlem|problem|formül|hesap", "Okul"],
        ["Tarih", "geçmiş|savaş|yıl|olay|ders", "Okul"],
        ["Coğrafya", "harita|ülke|dünya|iklim|ders", "Okul"],
        ["Biyoloji", "canlı|hücre|insan|bitki|bilim", "Okul"],
        ["Fizik", "kuvvet|enerji|hareket|bilim|formül", "Okul"],
        ["Kimya", "element|madde|deney|asit|laboratuvar", "Okul"],
        ["Teneffüs", "ders|ara|zil|okul|oynamak", "Okul"],
        ["Müdür", "okul|yönetmek|oda|öğretmen|disiplin", "Okul"],
        ["Servis", "okul|otobüs|öğrenci|şoför|taşımak", "Okul"],
        ["Karne", "not|dönem|öğrenci|belge|tatil", "Okul"],
        ["Ders", "öğretmen|öğrenmek|okul|konu|saat", "Okul"],

        ["Doktor", "hastane|hasta|muayene|ilaç|sağlık", "Meslekler"],
        ["Hemşire", "hasta|hastane|iğne|bakım|doktor", "Meslekler"],
        ["Mühendis", "tasarım|hesap|proje|teknik|inşaat", "Meslekler"],
        ["Mimar", "bina|çizim|proje|tasarım|plan", "Meslekler"],
        ["Avukat", "mahkeme|savunmak|hukuk|dava|müvekkil", "Meslekler"],
        ["Hakim", "mahkeme|karar|dava|adalet|cübbe", "Meslekler"],
        ["Polis", "güvenlik|suç|üniforma|karakol|siren", "Meslekler"],
        ["İtfaiyeci", "yangın|söndürmek|hortum|kırmızı|kurtarmak", "Meslekler"],
        ["Aşçı", "mutfak|yemek|pişirmek|şef|tencere", "Meslekler"],
        ["Garson", "restoran|sipariş|masa|servis|bahşiş", "Meslekler"],
        ["Pilot", "uçak|uçmak|kokpit|hava|kaptan", "Meslekler"],
        ["Hostes", "uçak|yolcu|servis|kabin|hava", "Meslekler"],
        ["Çiftçi", "tarla|toprak|ürün|traktör|köy", "Meslekler"],
        ["Terzi", "dikmek|kumaş|iğne|iplik|kıyafet", "Meslekler"],
        ["Berber", "saç|kesmek|tıraş|makas|dükkan", "Meslekler"],
        ["Gazeteci", "haber|röportaj|gazete|yazmak|basın", "Meslekler"],
        ["Fotoğrafçı", "kamera|çekmek|poz|stüdyo|resim", "Meslekler"],
        ["Veteriner", "hayvan|doktor|klinik|tedavi|evcil", "Meslekler"],
        ["Diş Hekimi", "diş|muayene|dolgu|ağız|klinik", "Meslekler"],
        ["Eczacı", "ilaç|reçete|eczane|hasta|sağlık", "Meslekler"],
        ["Akademisyen", "üniversite|araştırma|ders|makale|profesör", "Meslekler"],
        ["Elektrikçi", "kablo|priz|akım|tamir|sigorta", "Meslekler"],
        ["Tesisatçı", "boru|su|musluk|tamir|sızıntı", "Meslekler"],
        ["Oyuncu", "rol|film|sahne|kamera|tiyatro", "Meslekler"],
        ["Müzisyen", "müzik|enstrüman|şarkı|konser|çalmak", "Meslekler"],

        ["İstanbul", "Boğaz|Türkiye|kalabalık|Ayasofya|şehir", "Şehir ve Gezi"],
        ["Ankara", "başkent|Türkiye|Anıtkabir|meclis|şehir", "Şehir ve Gezi"],
        ["İzmir", "Ege|Kordon|şehir|deniz|saat kulesi", "Şehir ve Gezi"],
        ["Antalya", "tatil|Akdeniz|plaj|turist|sıcak", "Şehir ve Gezi"],
        ["Kapadokya", "balon|peri bacası|Nevşehir|turist|vadi", "Şehir ve Gezi"],
        ["Paris", "Fransa|Eyfel|şehir|aşk|Seine", "Şehir ve Gezi"],
        ["Londra", "İngiltere|Big Ben|şehir|kraliçe|yağmur", "Şehir ve Gezi"],
        ["Roma", "İtalya|Kolezyum|şehir|tarih|Vatikan", "Şehir ve Gezi"],
        ["New York", "Amerika|Manhattan|şehir|Özgürlük Heykeli|gökdelen", "Şehir ve Gezi"],
        ["Tokyo", "Japonya|şehir|kalabalık|teknoloji|metro", "Şehir ve Gezi"],
        ["Otel", "oda|tatil|resepsiyon|gece|konaklamak", "Şehir ve Gezi"],
        ["Pasaport", "yurt dışı|kimlik|sınır|belge|vize", "Şehir ve Gezi"],
        ["Bavul", "seyahat|eşya|tekerlek|hazırlamak|bagaj", "Şehir ve Gezi"],
        ["Uçak", "uçmak|kanat|pilot|havalimanı|yolcu", "Şehir ve Gezi"],
        ["Tren", "ray|istasyon|vagon|yolculuk|lokomotif", "Şehir ve Gezi"],
        ["Otobüs", "durak|şoför|yolcu|bilet|toplu taşıma", "Şehir ve Gezi"],
        ["Gemi", "deniz|kaptan|liman|güverte|yolcu", "Şehir ve Gezi"],
        ["Havalimanı", "uçak|terminal|bagaj|uçuş|pasaport", "Şehir ve Gezi"],
        ["İstasyon", "tren|ray|peron|beklemek|yolcu", "Şehir ve Gezi"],
        ["Harita", "yol|ülke|yön|çizim|bulmak", "Şehir ve Gezi"],
        ["Tatil", "dinlenmek|otel|yaz|seyahat|izin", "Şehir ve Gezi"],
        ["Kamp", "çadır|doğa|ateş|uyumak|orman", "Şehir ve Gezi"],
        ["Plaj", "deniz|kum|güneş|yüzmek|şemsiye", "Şehir ve Gezi"],
        ["Müze", "eser|tarih|sergi|gezmek|sanat", "Şehir ve Gezi"],
        ["Rehber", "turist|anlatmak|gezi|yol|bilgi", "Şehir ve Gezi"],

        ["Pizza", "İtalya|peynir|hamur|dilim|fırın", "Yemek"],
        ["Hamburger", "ekmek|köfte|fast food|patates|sos", "Yemek"],
        ["Kebap", "et|şiş|mangal|Adana|acı", "Yemek"],
        ["Mantı", "hamur|yoğurt|kıyma|küçük|Kayseri", "Yemek"],
        ["Baklava", "tatlı|fıstık|şerbet|yufka|dilim", "Yemek"],
        ["Çorba", "sıcak|kaşık|kase|mercimek|içmek", "Yemek"],
        ["Makarna", "İtalya|sos|haşlamak|spagetti|hamur", "Yemek"],
        ["Pilav", "pirinç|bulgur|tane|tencere|yemek", "Yemek"],
        ["Salata", "sebze|yeşillik|domates|limon|sağlıklı", "Yemek"],
        ["Dondurma", "soğuk|külah|yaz|erimek|tatlı", "Yemek"],
        ["Çikolata", "kakao|tatlı|sütlü|bitter|paket", "Yemek"],
        ["Kahve", "fincan|kafein|Türk|içmek|sıcak", "Yemek"],
        ["Çay", "bardak|demlemek|sıcak|Rize|içmek", "Yemek"],
        ["Ekmek", "fırın|un|dilim|hamur|sofra", "Yemek"],
        ["Peynir", "süt|kahvaltı|beyaz|kaşar|dilim", "Yemek"],
        ["Zeytin", "siyah|yeşil|kahvaltı|yağ|çekirdek", "Yemek"],
        ["Yumurta", "tavuk|kahvaltı|sarısı|kabuk|haşlamak", "Yemek"],
        ["Balık", "deniz|yüzmek|kılçık|tava|solungaç", "Yemek"],
        ["Tavuk", "kanat|yumurta|kümes|et|gaga", "Yemek"],
        ["Patates", "kızartma|sebze|cips|toprak|püre", "Yemek"],
        ["Domates", "kırmızı|sebze|salata|sos|çekirdek", "Yemek"],
        ["Elma", "meyve|kırmızı|yeşil|ısırmak|ağaç", "Yemek"],
        ["Muz", "sarı|meyve|kabuk|maymun|salkım", "Yemek"],
        ["Portakal", "turuncu|meyve|vitamin|sıkmak|kabuk", "Yemek"],
        ["Pasta", "doğum günü|mum|tatlı|dilim|krema", "Yemek"],

        ["Güneş", "sıcak|ışık|gökyüzü|sarı|gündüz", "Doğa"],
        ["Ay", "gece|gökyüzü|Dünya|dolunay|uydu", "Doğa"],
        ["Yıldız", "gökyüzü|gece|parlamak|uzay|beş köşe", "Doğa"],
        ["Bulut", "gökyüzü|yağmur|beyaz|hava|gri", "Doğa"],
        ["Yağmur", "ıslanmak|damla|şemsiye|bulut|hava", "Doğa"],
        ["Kar", "beyaz|kış|soğuk|yağmak|kardan adam", "Doğa"],
        ["Rüzgar", "esmek|hava|yel|uçurmak|serin", "Doğa"],
        ["Fırtına", "rüzgar|yağmur|şiddetli|hava|dalga", "Doğa"],
        ["Deniz", "su|tuzlu|dalga|yüzmek|sahil", "Doğa"],
        ["Okyanus", "büyük|su|deniz|derin|kıta", "Doğa"],
        ["Nehir", "su|akmak|yatak|köprü|ırmak", "Doğa"],
        ["Göl", "su|kara|durgun|kıyı|balık", "Doğa"],
        ["Dağ", "yüksek|zirve|tırmanmak|kar|tepe", "Doğa"],
        ["Orman", "ağaç|yeşil|hayvan|doğa|yürümek", "Doğa"],
        ["Çöl", "kum|sıcak|deve|kurak|vaha", "Doğa"],
        ["Ada", "deniz|kara|etraf|kıyı|yalnız", "Doğa"],
        ["Volkan", "lav|patlamak|dağ|ateş|kül", "Doğa"],
        ["Deprem", "sarsıntı|yer|fay|bina|afet", "Doğa"],
        ["Gökkuşağı", "renk|yağmur|gökyüzü|yedi|yay", "Doğa"],
        ["Ağaç", "dal|yaprak|gövde|orman|kök", "Doğa"],
        ["Çiçek", "koku|renk|bahçe|yaprak|buket", "Doğa"],
        ["Toprak", "yer|bitki|kahverengi|tarla|çamur", "Doğa"],
        ["Mevsim", "yaz|kış|ilkbahar|sonbahar|dört", "Doğa"],
        ["Şelale", "su|akmak|yüksek|doğa|çağlayan", "Doğa"],
        ["Mağara", "karanlık|kaya|yer altı|yarasa|giriş", "Doğa"],

        ["Müzik", "ses|şarkı|dinlemek|nota|ritim", "Kültür ve Sanat"],
        ["Sinema", "film|salon|perde|izlemek|patlamış mısır", "Kültür ve Sanat"],
        ["Tiyatro", "sahne|oyuncu|perde|seyirci|oyun", "Kültür ve Sanat"],
        ["Roman", "kitap|yazar|hikaye|okumak|uzun", "Kültür ve Sanat"],
        ["Şiir", "dize|şair|kafiye|duygu|okumak", "Kültür ve Sanat"],
        ["Heykel", "taş|sanat|yontmak|müze|figür", "Kültür ve Sanat"],
        ["Resim", "boya|tuval|çizmek|renk|sanat", "Kültür ve Sanat"],
        ["Dans", "müzik|hareket|ritim|oynamak|sahne", "Kültür ve Sanat"],
        ["Konser", "müzik|sahne|şarkıcı|kalabalık|bilet", "Kültür ve Sanat"],
        ["Festival", "etkinlik|kalabalık|müzik|kutlama|açık hava", "Kültür ve Sanat"],
        ["Opera", "sahne|şarkı|orkestra|yüksek ses|sanat", "Kültür ve Sanat"],
        ["Sahne", "oyuncu|perde|tiyatro|ışık|seyirci", "Kültür ve Sanat"],
        ["Alkış", "el|seyirci|beğenmek|ses|sahne", "Kültür ve Sanat"],
        ["Yönetmen", "film|kamera|oyuncu|çekim|senaryo", "Kültür ve Sanat"],
        ["Yazar", "kitap|yazmak|roman|kalem|eser", "Kültür ve Sanat"],
        ["Şair", "şiir|dize|yazmak|duygu|kafiye", "Kültür ve Sanat"],
        ["Besteci", "müzik|nota|şarkı|yazmak|melodi", "Kültür ve Sanat"],
        ["Gitar", "tel|çalmak|müzik|pena|enstrüman", "Kültür ve Sanat"],
        ["Piyano", "tuş|çalmak|siyah|beyaz|enstrüman", "Kültür ve Sanat"],
        ["Keman", "yay|tel|çalmak|omuz|enstrüman", "Kültür ve Sanat"],
        ["Davul", "ritim|vurmak|baget|ses|enstrüman", "Kültür ve Sanat"],
        ["Sergi", "eser|sanat|galeri|gezmek|açılış", "Kültür ve Sanat"],
        ["Masal", "çocuk|hikaye|prenses|okumak|hayal", "Kültür ve Sanat"],
        ["Karikatür", "çizmek|mizah|gazete|komik|resim", "Kültür ve Sanat"],
        ["Bale", "dans|parmak ucu|sahne|etek|müzik", "Kültür ve Sanat"],

        ["Film", "sinema|izlemek|oyuncu|yönetmen|perde", "Sinema ve Televizyon"],
        ["Dizi", "bölüm|sezon|televizyon|izlemek|karakter", "Sinema ve Televizyon"],
        ["Komedi", "gülmek|komik|film|mizah|kahkaha", "Sinema ve Televizyon"],
        ["Korku", "korkmak|gerilim|film|hayalet|karanlık", "Sinema ve Televizyon"],
        ["Aksiyon", "film|kovalamaca|patlama|kahraman|hız", "Sinema ve Televizyon"],
        ["Belgesel", "gerçek|bilgi|doğa|izlemek|anlatıcı", "Sinema ve Televizyon"],
        ["Animasyon", "çizgi|karakter|film|hareket|çocuk", "Sinema ve Televizyon"],
        ["Fragman", "film|tanıtım|kısa|sinema|izlemek", "Sinema ve Televizyon"],
        ["Senaryo", "yazmak|film|hikaye|sahne|diyalog", "Sinema ve Televizyon"],
        ["Perde", "sinema|tiyatro|açılmak|kapanmak|kumaş", "Sinema ve Televizyon"],
        ["Oscar", "ödül|film|Hollywood|heykel|tören", "Sinema ve Televizyon"],
        ["Hollywood", "Amerika|film|oyuncu|sinema|Los Angeles", "Sinema ve Televizyon"],
        ["Netflix", "dizi|film|internet|izlemek|platform", "Sinema ve Televizyon"],
        ["Televizyon", "ekran|kanal|izlemek|kumanda|yayın", "Sinema ve Televizyon"],
        ["Kumanda", "televizyon|tuş|kanal|uzaktan|pil", "Sinema ve Televizyon"],
        ["Haber", "gazete|televizyon|sunucu|güncel|olay", "Sinema ve Televizyon"],
        ["Reklam", "ürün|tanıtım|televizyon|satmak|kısa", "Sinema ve Televizyon"],
        ["Yarışma", "ödül|soru|katılmak|televizyon|kazanmak", "Sinema ve Televizyon"],
        ["Sunucu", "program|televizyon|anlatmak|mikrofon|ekran", "Sinema ve Televizyon"],
        ["Bölüm", "dizi|sezon|parça|izlemek|yeni", "Sinema ve Televizyon"],
        ["Sezon", "dizi|bölüm|yıl|final|yeni", "Sinema ve Televizyon"],
        ["Karakter", "rol|hikaye|oyuncu|kişilik|kahraman", "Sinema ve Televizyon"],
        ["Kahraman", "kurtarmak|güç|iyi|hikaye|cesur", "Sinema ve Televizyon"],
        ["Kötü Adam", "düşman|kahraman|film|kötülük|yenilmek", "Sinema ve Televizyon"],
        ["İzleyici", "seyretmek|ekran|seyirci|program|televizyon", "Sinema ve Televizyon"],

        ["Dünya", "gezegen|insan|yuvarlak|uzay|ülke", "Genel Bilgi"],
        ["Ülke", "devlet|bayrak|sınır|başkent|millet", "Genel Bilgi"],
        ["Bayrak", "ülke|dalgalanmak|renk|sembol|direk", "Genel Bilgi"],
        ["Para", "alışveriş|banknot|madeni|ödemek|değer", "Genel Bilgi"],
        ["Seçim", "oy|sandık|aday|halk|kazanmak", "Genel Bilgi"],
        ["Başkan", "yönetmek|ülke|seçim|lider|makam", "Genel Bilgi"],
        ["Kral", "taht|saray|taç|ülke|hükümdar", "Genel Bilgi"],
        ["Kraliçe", "taç|saray|kral|taht|hükümdar", "Genel Bilgi"],
        ["Savaş", "ordu|silah|düşman|ülke|barış", "Genel Bilgi"],
        ["Barış", "savaş|huzur|anlaşma|dostluk|güvercin", "Genel Bilgi"],
        ["Takvim", "gün|ay|yıl|tarih|duvar", "Genel Bilgi"],
        ["Zaman", "saat|geçmek|geçmiş|gelecek|an", "Genel Bilgi"],
        ["Dil", "konuşmak|kelime|ülke|ağız|iletişim", "Genel Bilgi"],
        ["Alfabe", "harf|sıra|yazı|dil|A", "Genel Bilgi"],
        ["Sayı", "rakam|matematik|saymak|işlem|adet", "Genel Bilgi"],
        ["Renk", "boya|görmek|kırmızı|mavi|ton", "Genel Bilgi"],
        ["Enerji", "güç|elektrik|hareket|kaynak|tüketmek", "Genel Bilgi"],
        ["Elektrik", "akım|priz|enerji|kablo|çarpılmak", "Genel Bilgi"],
        ["Mıknatıs", "çekmek|metal|kutup|demir|manyetik", "Genel Bilgi"],
        ["Gezegen", "uzay|Dünya|yörünge|Güneş|yuvarlak", "Genel Bilgi"],
        ["Uzay", "yıldız|gezegen|astronot|boşluk|roket", "Genel Bilgi"],
        ["Roket", "uzay|fırlatmak|astronot|hız|motor", "Genel Bilgi"],
        ["Uydu", "uzay|yörünge|iletişim|Dünya|sinyal", "Genel Bilgi"],
        ["Pusula", "yön|kuzey|iğne|harita|manyetik", "Genel Bilgi"],
        ["Termometre", "sıcaklık|derece|ölçmek|ateş|cıva", "Genel Bilgi"],

        ["Kedi", "miyavlamak|pati|evcil|fare|tüy", "Hayvanlar"],
        ["Köpek", "havlamak|sadık|evcil|kuyruk|kemik", "Hayvanlar"],
        ["Aslan", "kral|orman|yele|kükremek|vahşi", "Hayvanlar"],
        ["Kaplan", "çizgi|turuncu|vahşi|kedi|orman", "Hayvanlar"],
        ["Fil", "hortum|büyük|kulak|Afrika|fildişi", "Hayvanlar"],
        ["Zürafa", "uzun|boyun|Afrika|benek|ağaç", "Hayvanlar"],
        ["Maymun", "muz|ağaç|kuyruk|orman|taklit", "Hayvanlar"],
        ["Ayı", "bal|kış uykusu|orman|büyük|pençe", "Hayvanlar"],
        ["Kurt", "uluma|sürü|orman|vahşi|köpek", "Hayvanlar"],
        ["Tilki", "kurnaz|kuyruk|orman|turuncu|tavuk", "Hayvanlar"],
        ["Tavşan", "havuç|uzun kulak|zıplamak|hızlı|yuva", "Hayvanlar"],
        ["At", "binmek|koşmak|eyer|nal|kişnemek", "Hayvanlar"],
        ["İnek", "süt|mölemek|çiftlik|boynuz|ot", "Hayvanlar"],
        ["Koyun", "yün|sürü|melemek|çoban|ot", "Hayvanlar"],
        ["Keçi", "boynuz|inatçı|dağ|süt|ot", "Hayvanlar"],
        ["Horoz", "ötmek|sabah|kümes|ibik|tavuk", "Hayvanlar"],
        ["Kartal", "uçmak|kanat|yırtıcı|gaga|yüksek", "Hayvanlar"],
        ["Güvercin", "uçmak|barış|kuş|meydan|kanat", "Hayvanlar"],
        ["Penguen", "buz|siyah beyaz|Antarktika|kuş|yüzmek", "Hayvanlar"],
        ["Yunus", "deniz|akıllı|yüzmek|balık|zıplamak", "Hayvanlar"],
        ["Balina", "okyanus|büyük|memeli|su|kuyruk", "Hayvanlar"],
        ["Köpekbalığı", "deniz|diş|yırtıcı|yüzgeç|korku", "Hayvanlar"],
        ["Kaplumbağa", "kabuk|yavaş|sürünmek|uzun yaşam|deniz", "Hayvanlar"],
        ["Yılan", "sürünmek|zehir|uzun|tıslamak|deri", "Hayvanlar"],
        ["Arı", "bal|kovan|sokmak|çiçek|kanat", "Hayvanlar"],
    ];

    return Object.freeze(rows.map(([word, forbidden, category], index) => Object.freeze({
        id: index,
        word,
        forbidden: Object.freeze(forbidden.split("|")),
        category,
    })));
});
