window.ParollaQuestions = [
    { letter: "A", question: "Türkiye Cumhuriyeti'nin başkenti.", answers: ["ankara"], category: "Coğrafya", points: 10 },
    { letter: "A", question: "Gök cisimlerini ve evreni inceleyen bilim dalı.", answers: ["astronomi"], category: "Bilim", points: 10 },
    { letter: "A", question: "Taşıdığı su miktarı bakımından dünyanın en büyük nehri.", answers: ["amazon", "amazon nehri"], category: "Coğrafya", points: 10 },
    { letter: "A", question: "Türkiye Cumhuriyeti'nin kurucusunun soyadı.", answers: ["atatürk", "mustafa kemal atatürk"], category: "Tarih", points: 10 },
    { letter: "A", question: "Türkiye'nin güney kıyılarının açıldığı deniz.", answers: ["akdeniz"], category: "Coğrafya", points: 10 },
    { letter: "A", question: "Türkiye'nin en yüksek dağı.", answers: ["ağrı dağı", "ağrı"], category: "Coğrafya", points: 10 },

    { letter: "B", question: "Dünyanın en derin gölü.", answers: ["baykal", "baykal gölü", "baikal", "baikal gölü"], category: "Coğrafya", points: 10 },
    { letter: "B", question: "Dokuzuncu Senfoni'nin bestecisi.", answers: ["beethoven", "ludwig van beethoven"], category: "Müzik", points: 10 },
    { letter: "B", question: "Asma Bahçeleri ile ilişkilendirilen antik kent.", answers: ["babil"], category: "Tarih", points: 10 },
    { letter: "B", question: "Asya ile Kuzey Amerika'yı ayıran boğaz.", answers: ["bering", "bering boğazı"], category: "Coğrafya", points: 10 },
    { letter: "B", question: "Başkenti Saraybosna olan Balkan ülkesi.", answers: ["bosna hersek", "bosna-hersek"], category: "Coğrafya", points: 10 },
    { letter: "B", question: "Kar üzerinde birikip zamanla hareket eden büyük buz kütlesi.", answers: ["buzul"], category: "Doğa", points: 10 },

    { letter: "C", question: "Atlas Okyanusu ile Akdeniz'i birbirine bağlayan boğaz.", answers: ["cebelitarık", "cebelitarık boğazı"], category: "Coğrafya", points: 10 },
    { letter: "C", question: "Suyun donma noktasını 0 derece kabul eden sıcaklık ölçeği.", answers: ["celsius", "selsiyus", "santigrat"], category: "Bilim", points: 10 },
    { letter: "C", question: "\"Otuz Beş Yaş\" şiirinin şairi.", answers: ["cahit sıtkı tarancı", "cahit sıtkı"], category: "Edebiyat", points: 10 },
    { letter: "C", question: "Uluslararası Kızılhaç Komitesinin merkezinin bulunduğu İsviçre şehri.", answers: ["cenevre"], category: "Genel Kültür", points: 10 },
    { letter: "C", question: "İki farklı bilim dalında Nobel Ödülü alan Marie'nin soyadı.", answers: ["curie", "küri", "marie curie"], category: "Bilim", points: 10 },
    { letter: "C", question: "Yüz ölçümü bakımından Afrika'nın en büyük ülkesi.", answers: ["cezayir"], category: "Coğrafya", points: 10 },

    { letter: "Ç", question: "Ege Denizi ile Marmara Denizi'ni birbirine bağlayan boğaz.", answers: ["çanakkale", "çanakkale boğazı"], category: "Coğrafya", points: 10 },
    { letter: "Ç", question: "Karada yaşayan en hızlı hayvan.", answers: ["çita"], category: "Doğa", points: 10 },
    { letter: "Ç", question: "Seddi ile tanınan ve başkenti Pekin olan ülke.", answers: ["çin"], category: "Coğrafya", points: 10 },
    { letter: "Ç", question: "Konya'da bulunan önemli Neolitik Çağ yerleşimi.", answers: ["çatalhöyük"], category: "Tarih", points: 10 },
    { letter: "Ç", question: "Başkenti Prag olan Orta Avrupa ülkesi.", answers: ["çekya", "çek cumhuriyeti"], category: "Coğrafya", points: 10 },
    { letter: "Ç", question: "Artvin'den geçerek Gürcistan'a ulaşan, rafting parkurlarıyla ünlü nehir.", answers: ["çoruh", "çoruh nehri"], category: "Coğrafya", points: 10 },

    { letter: "D", question: "Güneş'e yakınlık bakımından üçüncü gezegen.", answers: ["dünya"], category: "Bilim", points: 10 },
    { letter: "D", question: "Doğal seçilim yoluyla evrim kuramıyla tanınan bilim insanının soyadı.", answers: ["darwin", "charles darwin"], category: "Bilim", points: 10 },
    { letter: "D", question: "\"Suç ve Ceza\" romanının yazarı.", answers: ["dostoyevski", "dostoyevsky", "dostoevsky", "fyodor dostoyevski"], category: "Edebiyat", points: 10 },
    { letter: "D", question: "Kuzey Amerika'nın en yüksek dağı.", answers: ["denali"], category: "Coğrafya", points: 10 },
    { letter: "D", question: "Fırat ile birlikte Mezopotamya'ya hayat veren nehir.", answers: ["dicle", "dicle nehri"], category: "Coğrafya", points: 10 },
    { letter: "D", question: "Canlıların kalıtsal bilgisini taşıyan molekülün kısa adı.", answers: ["dna"], category: "Bilim", points: 10 },

    { letter: "E", question: "Dünya'yı kuzey ve güney yarım kürelere ayıran hayali çizgi.", answers: ["ekvator"], category: "Coğrafya", points: 10 },
    { letter: "E", question: "Deniz seviyesine göre dünyanın en yüksek dağı.", answers: ["everest", "everest dağı"], category: "Coğrafya", points: 10 },
    { letter: "E", question: "Türkiye'nin batısı ile Yunanistan arasında bulunan deniz.", answers: ["ege", "ege denizi"], category: "Coğrafya", points: 10 },
    { letter: "E", question: "Görelilik kuramıyla tanınan fizikçinin soyadı.", answers: ["einstein", "albert einstein"], category: "Bilim", points: 10 },
    { letter: "E", question: "Fonografı geliştiren Amerikalı mucidin soyadı.", answers: ["edison", "thomas edison"], category: "Bilim", points: 10 },
    { letter: "E", question: "İzmir'in Selçuk ilçesi yakınlarında bulunan antik kent.", answers: ["efes"], category: "Tarih", points: 10 },

    { letter: "F", question: "Dicle ile birlikte Mezopotamya'nın iki büyük nehrinden biri.", answers: ["fırat", "fırat nehri"], category: "Coğrafya", points: 10 },
    { letter: "F", question: "Penisilini keşfeden bilim insanının soyadı.", answers: ["fleming", "alexander fleming"], category: "Bilim", points: 10 },
    { letter: "F", question: "Başkenti Paris olan Avrupa ülkesi.", answers: ["fransa"], category: "Coğrafya", points: 10 },
    { letter: "F", question: "Geçmiş çağlarda yaşamış canlıların taşlaşmış kalıntısı veya izi.", answers: ["fosil"], category: "Bilim", points: 10 },
    { letter: "F", question: "Japonya'nın en yüksek dağı.", answers: ["fuji", "fuji dağı", "fujiyama"], category: "Coğrafya", points: 10 },
    { letter: "F", question: "\"Muallim-i Sani\" unvanıyla anılan Türk-İslam filozofu.", answers: ["farabi", "el farabi"], category: "Tarih", points: 10 },

    { letter: "G", question: "Teleskop gözlemleriyle Güneş merkezli evren modelini destekleyen İtalyan bilim insanı.", answers: ["galileo", "galileo galilei"], category: "Bilim", points: 10 },
    { letter: "G", question: "Kıta sayılmayan dünyanın en büyük adası.", answers: ["grönland"], category: "Coğrafya", points: 10 },
    { letter: "G", question: "Avrupa'da hareketli harflerle baskıyı yaygınlaştıran mucidin soyadı.", answers: ["gutenberg", "johannes gutenberg"], category: "Tarih", points: 10 },
    { letter: "G", question: "Hindular tarafından kutsal kabul edilen nehir.", answers: ["ganj", "ganj nehri"], category: "Coğrafya", points: 10 },
    { letter: "G", question: "Friglerin başkenti olan ve Ankara'nın Polatlı ilçesinde bulunan antik kent.", answers: ["gordion", "gordiyon"], category: "Tarih", points: 10 },
    { letter: "G", question: "Şanlıurfa'da bulunan, anıtsal dikilitaşlarıyla tanınan tarih öncesi yerleşim.", answers: ["göbeklitepe", "göbekli tepe"], category: "Tarih", points: 10 },

    { letter: "H", question: "Everest'in de içinde bulunduğu Asya'daki dağ sırası.", answers: ["himalayalar", "himalaya", "himalaya dağları"], category: "Coğrafya", points: 10 },
    { letter: "H", question: "Hitit İmparatorluğu'nun Çorum yakınlarındaki başkenti.", answers: ["hattuşa", "hattuşaş"], category: "Tarih", points: 10 },
    { letter: "H", question: "Simgesi He olan ve balonlarda kullanılan hafif element.", answers: ["helyum"], category: "Bilim", points: 10 },
    { letter: "H", question: "\"İlyada\" ve \"Odysseia\" destanlarının atfedildiği ozan.", answers: ["homeros", "homer"], category: "Edebiyat", points: 10 },
    { letter: "H", question: "Dünyanın en büyük kapalı su kütlesi.", answers: ["hazar", "hazar denizi"], category: "Coğrafya", points: 10 },
    { letter: "H", question: "Bodrum'un Antik Çağ'daki adı.", answers: ["halikarnas", "halikarnassos"], category: "Tarih", points: 10 },

    { letter: "I", question: "Başkenti Bağdat olan Orta Doğu ülkesi.", answers: ["ırak"], category: "Coğrafya", points: 10 },
    { letter: "I", question: "Genellikle denize, göle veya başka bir akarsuya dökülen büyük akarsu.", answers: ["ırmak"], category: "Coğrafya", points: 10 },
    { letter: "I", question: "Işığın boşlukta bir yılda aldığı yolu ifade eden uzaklık birimi.", answers: ["ışık yılı"], category: "Bilim", points: 10 },
    { letter: "I", question: "Çiçekleri kurutularak çayı yapılan kokulu ağaç.", answers: ["ıhlamur"], category: "Doğa", points: 10 },
    { letter: "I", question: "Gül yetiştiriciliği ve gül ürünleriyle tanınan Türkiye ili.", answers: ["ısparta"], category: "Coğrafya", points: 10 },
    { letter: "I", question: "Kastamonu ile Çankırı arasında uzanan dağ sırası.", answers: ["ılgaz", "ılgaz dağları"], category: "Coğrafya", points: 10 },

    { letter: "İ", question: "İki kıta üzerine kurulmuş, Boğaziçi kıyısındaki Türkiye şehri.", answers: ["istanbul"], category: "Coğrafya", points: 10 },
    { letter: "İ", question: "\"El-Kanun fi't-Tıb\" eseriyle tanınan hekim ve filozof.", answers: ["ibn sina", "ibni sina", "ibn-i sina", "avicenna"], category: "Tarih", points: 10 },
    { letter: "İ", question: "Einstein'ın görelilik kuramının Türkçedeki diğer adı.", answers: ["izafiyet"], category: "Bilim", points: 10 },
    { letter: "İ", question: "Çin ile Akdeniz arasında yüzyıllarca kullanılan tarihî ticaret yolu.", answers: ["ipek yolu"], category: "Tarih", points: 10 },
    { letter: "İ", question: "Başkenti Reykjavik olan ada ülkesi.", answers: ["izlanda"], category: "Coğrafya", points: 10 },
    { letter: "İ", question: "Efes ve Milet gibi kentleri kapsayan Batı Anadolu'daki antik bölge.", answers: ["iyonya"], category: "Tarih", points: 10 },

    { letter: "J", question: "Güneş Sistemi'nin en büyük gezegeni.", answers: ["jüpiter"], category: "Bilim", points: 10 },
    { letter: "J", question: "Başkenti Tokyo olan ada ülkesi.", answers: ["japonya"], category: "Coğrafya", points: 10 },
    { letter: "J", question: "Dünya'nın yapısını, kayaçları ve yer kabuğunu inceleyen bilim dalı.", answers: ["jeoloji"], category: "Bilim", points: 10 },
    { letter: "J", question: "Enerjinin uluslararası birim sistemindeki birimi.", answers: ["joule", "jul"], category: "Bilim", points: 10 },
    { letter: "J", question: "\"Denizler Altında Yirmi Bin Fersah\" romanının yazarı.", answers: ["jules verne", "jules vern", "jul vern", "jül vern", "jül verne"], category: "Edebiyat", points: 10 },
    { letter: "J", question: "Endonezya'nın başkenti Cakarta'nın bulunduğu ada.", answers: ["java", "cava"], category: "Coğrafya", points: 10 },

    { letter: "K", question: "Tamamı Türkiye sınırları içinde doğup denize dökülen en uzun nehir.", answers: ["kızılırmak", "kızılırmak nehri"], category: "Coğrafya", points: 10 },
    { letter: "K", question: "Tanzanya'da bulunan Afrika'nın en yüksek dağı.", answers: ["kilimanjaro"], category: "Coğrafya", points: 10 },
    { letter: "K", question: "\"Dönüşüm\" adlı uzun öykünün yazarı.", answers: ["kafka", "franz kafka"], category: "Edebiyat", points: 10 },
    { letter: "K", question: "Kuzey yönünü bulmada yararlanılan parlak yıldız.", answers: ["kutup yıldızı", "kutupyıldızı", "polaris"], category: "Bilim", points: 10 },
    { letter: "K", question: "Peribacaları ve yer altı şehirleriyle ünlü bölge.", answers: ["kapadokya"], category: "Coğrafya", points: 10 },
    { letter: "K", question: "Gize'deki Büyük Piramit'in adına yapıldığı firavun.", answers: ["keops", "khufu", "cheops"], category: "Tarih", points: 10 },

    { letter: "L", question: "\"Mona Lisa\" tablosunun ressamı.", answers: ["leonardo da vinci", "leonardo", "da vinci"], category: "Sanat", points: 10 },
    { letter: "L", question: "Thames Nehri kıyısında bulunan Birleşik Krallık başkenti.", answers: ["londra"], category: "Coğrafya", points: 10 },
    { letter: "L", question: "Periyodik tablodaki en hafif metal.", answers: ["lityum"], category: "Bilim", points: 10 },
    { letter: "L", question: "Ksantos ve Letoon gibi kentleri kapsayan antik Anadolu uygarlığı.", answers: ["likya"], category: "Tarih", points: 10 },
    { letter: "L", question: "Paris'te bulunan ve Mona Lisa'yı sergileyen müze.", answers: ["louvre", "louvre müzesi", "luvr"], category: "Sanat", points: 10 },
    { letter: "L", question: "Hayvan kahramanlı fabllarıyla tanınan Fransız yazar.", answers: ["la fontaine", "lafontaine", "jean de la fontaine"], category: "Edebiyat", points: 10 },

    { letter: "M", question: "Kızıl Gezegen olarak bilinen gezegen.", answers: ["mars"], category: "Bilim", points: 10 },
    { letter: "M", question: "Selimiye Camii'ni \"ustalık eserim\" diye nitelendiren mimar.", answers: ["mimar sinan", "sinan"], category: "Sanat", points: 10 },
    { letter: "M", question: "\"Sihirli Flüt\" operasının bestecisi.", answers: ["mozart", "wolfgang amadeus mozart"], category: "Müzik", points: 10 },
    { letter: "M", question: "Tamamı Türkiye sınırları içinde kalan deniz.", answers: ["marmara", "marmara denizi"], category: "Coğrafya", points: 10 },
    { letter: "M", question: "Metin ve görselleri çok sayıda kopya hâlinde basmaya yarayan araç.", answers: ["matbaa"], category: "Tarih", points: 10 },
    { letter: "M", question: "Peru'da, And Dağları üzerinde bulunan ünlü İnka yerleşimi.", answers: ["machu picchu", "machu pichu", "maçu piçu", "maçu pikçu"], category: "Tarih", points: 10 },

    { letter: "N", question: "Akdeniz'e dökülen ve Mısır'a hayat veren nehir.", answers: ["nil", "nil nehri"], category: "Coğrafya", points: 10 },
    { letter: "N", question: "Evrensel çekim yasasıyla tanınan bilim insanının soyadı.", answers: ["newton", "isaac newton"], category: "Bilim", points: 10 },
    { letter: "N", question: "Dev heykelleriyle tanınan, Adıyaman'daki dağ.", answers: ["nemrut", "nemrut dağı"], category: "Tarih", points: 10 },
    { letter: "N", question: "Dinamiti icat eden ve adına ödüller verilen bilim insanının soyadı.", answers: ["nobel", "alfred nobel"], category: "Bilim", points: 10 },
    { letter: "N", question: "Güneş Sistemi'nde Güneş'e en uzak sekizinci gezegen.", answers: ["neptün"], category: "Bilim", points: 10 },
    { letter: "N", question: "Kapadokya bölgesinin merkezindeki Türkiye ili.", answers: ["nevşehir"], category: "Coğrafya", points: 10 },

    { letter: "O", question: "Simgesi O olan ve solunum için gerekli element.", answers: ["oksijen"], category: "Bilim", points: 10 },
    { letter: "O", question: "Türk adının geçtiği bilinen en eski Türkçe metinler.", answers: ["orhun yazıtları", "orhun abideleri"], category: "Tarih", points: 10 },
    { letter: "O", question: "\"Kaplumbağa Terbiyecisi\" tablosunun ressamı.", answers: ["osman hamdi bey", "osman hamdi"], category: "Sanat", points: 10 },
    { letter: "O", question: "Yunan mitolojisinde tanrıların yaşadığı kabul edilen dağ.", answers: ["olimpos", "olimpos dağı", "olympos", "olympus"], category: "Mitoloji", points: 10 },
    { letter: "O", question: "Avustralya, Yeni Zelanda ve Pasifik adalarını kapsayan coğrafi bölge.", answers: ["okyanusya"], category: "Coğrafya", points: 10 },
    { letter: "O", question: "Antik Çağ ile Yeni Çağ arasındaki tarih dönemi.", answers: ["orta çağ", "ortaçağ"], category: "Tarih", points: 10 },

    { letter: "Ö", question: "Geometrinin temellerini sistemleştiren, \"Elementler\" adlı eserin yazarı.", answers: ["öklid", "öklit", "euclid", "eukleides"], category: "Bilim", points: 10 },
    { letter: "Ö", question: "Göktürk ve Uygur tarihinde kutsal merkez kabul edilen bölge.", answers: ["ötüken"], category: "Tarih", points: 10 },
    { letter: "Ö", question: "Rubaileriyle tanınan İranlı şair ve bilgin.", answers: ["ömer hayyam", "hayyam"], category: "Edebiyat", points: 10 },
    { letter: "Ö", question: "Sekiz bacağı bulunan eklem bacaklı hayvan.", answers: ["örümcek"], category: "Doğa", points: 10 },
    { letter: "Ö", question: "Semerkant ve Buhara şehirlerinin bulunduğu Orta Asya ülkesi.", answers: ["özbekistan"], category: "Coğrafya", points: 10 },
    { letter: "Ö", question: "Fethiye yakınlarında bulunan, lagünüyle ünlü turizm merkezi.", answers: ["ölüdeniz"], category: "Coğrafya", points: 10 },

    { letter: "P", question: "Dünyanın en büyük okyanusu.", answers: ["pasifik", "pasifik okyanusu", "büyük okyanus"], category: "Coğrafya", points: 10 },
    { letter: "P", question: "Kuduz aşısı ve mikrop kuramına katkılarıyla tanınan bilim insanının soyadı.", answers: ["pasteur", "pastör", "louis pasteur"], category: "Bilim", points: 10 },
    { letter: "P", question: "Eğik Kulesi ile tanınan İtalya şehri.", answers: ["pisa"], category: "Coğrafya", points: 10 },
    { letter: "P", question: "Atina'da Akademia adlı okulu kuran Antik Yunan filozofu.", answers: ["platon", "eflatun"], category: "Felsefe", points: 10 },
    { letter: "P", question: "Kıtaların ayrılmadan önce oluşturduğu varsayılan süper kıta.", answers: ["pangea"], category: "Bilim", points: 10 },
    { letter: "P", question: "Beyaz travertenleriyle tanınan Denizli ilçesi.", answers: ["pamukkale"], category: "Coğrafya", points: 10 },

    { letter: "R", question: "Avrupa'da 15. ve 16. yüzyıllarda sanat ve bilimde yaşanan yeniden doğuş hareketi.", answers: ["rönesans", "renaissance"], category: "Tarih", points: 10 },
    { letter: "R", question: "İtalya'nın başkenti.", answers: ["roma"], category: "Coğrafya", points: 10 },
    { letter: "R", question: "Kararsız atom çekirdeklerinin ışınım yayması olayı.", answers: ["radyoaktivite", "radyoaktiflik"], category: "Bilim", points: 10 },
    { letter: "R", question: "Atom çekirdeğinin varlığını altın levha deneyiyle gösteren bilim insanının soyadı.", answers: ["rutherford", "ernest rutherford"], category: "Bilim", points: 10 },
    { letter: "R", question: "Çay üretimiyle tanınan Karadeniz ili.", answers: ["rize"], category: "Coğrafya", points: 10 },
    { letter: "R", question: "Altı yüzünde farklı renkler bulunan döner mekanizmalı zekâ oyunu.", answers: ["rubik küpü", "rubik küp", "rubik"], category: "Genel Kültür", points: 10 },

    { letter: "S", question: "Belirgin halkalarıyla tanınan Güneş Sistemi gezegeni.", answers: ["satürn"], category: "Bilim", points: 10 },
    { letter: "S", question: "Çivi yazısını geliştiren Mezopotamya uygarlığı.", answers: ["sümerler", "sümer"], category: "Tarih", points: 10 },
    { letter: "S", question: "Düşüncelerini soru-cevap yöntemiyle aktaran Antik Yunan filozofu.", answers: ["sokrates"], category: "Felsefe", points: 10 },
    { letter: "S", question: "Kuzey Afrika'nın büyük bölümünü kaplayan çöl.", answers: ["sahra", "sahra çölü"], category: "Coğrafya", points: 10 },
    { letter: "S", question: "Osmanlı evleriyle tanınan ve UNESCO Dünya Mirası Listesi'ndeki Karabük ilçesi.", answers: ["safranbolu"], category: "Kültür", points: 10 },
    { letter: "S", question: "Rusya'nın büyük bölümünü kaplayan, sert kışlarıyla tanınan bölge.", answers: ["sibirya"], category: "Coğrafya", points: 10 },

    { letter: "Ş", question: "Güney Amerika'nın batı kıyısında kuzeyden güneye uzanan ince ülke.", answers: ["şili"], category: "Coğrafya", points: 10 },
    { letter: "Ş", question: "Suriye'nin başkenti.", answers: ["şam"], category: "Coğrafya", points: 10 },
    { letter: "Ş", question: "Japonya'nın geleneksel yerel dini.", answers: ["şintoizm", "şinto"], category: "Kültür", points: 10 },
    { letter: "Ş", question: "Orta Çağ Avrupa'sında atlı savaşçı sınıfına verilen ad.", answers: ["şövalye"], category: "Tarih", points: 10 },
    { letter: "Ş", question: "Göbeklitepe'nin bulunduğu Türkiye ili.", answers: ["şanlıurfa", "urfa"], category: "Coğrafya", points: 10 },
    { letter: "Ş", question: "Firdevsi'nin İran mitolojisi ve tarihini anlatan destansı eseri.", answers: ["şehname"], category: "Edebiyat", points: 10 },

    { letter: "T", question: "Avrupa'da en fazla ülkeden geçen nehir.", answers: ["tuna", "tuna nehri"], category: "Coğrafya", points: 10 },
    { letter: "T", question: "Alternatif akım sistemleriyle tanınan mucidin soyadı.", answers: ["tesla", "nikola tesla"], category: "Bilim", points: 10 },
    { letter: "T", question: "Homeros'un İlyada destanına konu olan antik kent.", answers: ["troya", "truva"], category: "Tarih", points: 10 },
    { letter: "T", question: "1912'de ilk seferinde batan ünlü yolcu gemisi.", answers: ["titanik", "titanic"], category: "Tarih", points: 10 },
    { letter: "T", question: "Osmanlı Devleti'nde 1839 Gülhane Hatt-ı Hümayunu ile başlayan yenileşme dönemi.", answers: ["tanzimat", "tanzimat dönemi"], category: "Tarih", points: 10 },
    { letter: "T", question: "Uzak gök cisimlerini daha büyük görmeyi sağlayan optik araç.", answers: ["teleskop"], category: "Bilim", points: 10 },

    { letter: "U", question: "Atom numarası 92 olan radyoaktif element.", answers: ["uranyum"], category: "Bilim", points: 10 },
    { letter: "U", question: "Avrupa ile Asya arasında doğal sınır kabul edilen dağ sırası.", answers: ["ural", "ural dağları"], category: "Coğrafya", points: 10 },
    { letter: "U", question: "Birleşmiş Milletlerin eğitim, bilim ve kültür kuruluşunun kısa adı.", answers: ["unesco"], category: "Genel Kültür", points: 10 },
    { letter: "U", question: "Yerleşik yaşama ve şehir kültürüne önem veren tarihî Türk topluluğu.", answers: ["uygurlar", "uygur"], category: "Tarih", points: 10 },
    { letter: "U", question: "Bursa'nın güneyinde bulunan ve kayak merkeziyle tanınan dağ.", answers: ["uludağ"], category: "Coğrafya", points: 10 },
    { letter: "U", question: "Van Gölü çevresinde güçlü bir devlet kuran Demir Çağı uygarlığı.", answers: ["urartu", "urartular"], category: "Tarih", points: 10 },

    { letter: "Ü", question: "Afrika'nın güney ucuna yakın, tarihî deniz rotasıyla tanınan burun.", answers: ["ümit burnu"], category: "Coğrafya", points: 10 },
    { letter: "Ü", question: "Başkenti Amman olan Orta Doğu ülkesi.", answers: ["ürdün"], category: "Coğrafya", points: 10 },
    { letter: "Ü", question: "Üç kenarı ve üç köşesi bulunan geometrik şekil.", answers: ["üçgen"], category: "Matematik", points: 10 },
    { letter: "Ü", question: "Kuzey Makedonya'nın başkenti.", answers: ["üsküp"], category: "Coğrafya", points: 10 },
    { letter: "Ü", question: "Ata binerken ayağın geçirildiği, eyerin iki yanındaki destek.", answers: ["üzengi"], category: "Genel Kültür", points: 10 },
    { letter: "Ü", question: "Thomas More'un ideal toplum düzenini anlattığı eser ve kavram.", answers: ["ütopya"], category: "Edebiyat", points: 10 },

    { letter: "V", question: "Güneş Sistemi'nin en sıcak gezegeni.", answers: ["venüs"], category: "Bilim", points: 10 },
    { letter: "V", question: "\"Yıldızlı Gece\" tablosunun ressamının soyadı.", answers: ["van gogh", "van gog", "vincent van gogh"], category: "Sanat", points: 10 },
    { letter: "V", question: "Avrupa'nın en uzun nehri.", answers: ["volga", "volga nehri"], category: "Coğrafya", points: 10 },
    { letter: "V", question: "Avusturya'nın başkenti.", answers: ["viyana"], category: "Coğrafya", points: 10 },
    { letter: "V", question: "Pompeii antik kentinin yok oluşuyla ilişkilendirilen yanardağ.", answers: ["vezüv", "vezüv yanardağı"], category: "Tarih", points: 10 },
    { letter: "V", question: "8. ve 11. yüzyıllar arasında Avrupa denizlerinde etkili olan İskandinav denizcisi.", answers: ["viking", "vikingler"], category: "Tarih", points: 10 },

    { letter: "Y", question: "Başkenti Atina olan ülke.", answers: ["yunanistan"], category: "Coğrafya", points: 10 },
    { letter: "Y", question: "Kendi ışığını üreten büyük gök cismi.", answers: ["yıldız"], category: "Bilim", points: 10 },
    { letter: "Y", question: "Granit kayalıkları ve şelaleleriyle tanınan Kaliforniya'daki millî park.", answers: ["yosemite", "yosemite ulusal parkı"], category: "Coğrafya", points: 10 },
    { letter: "Y", question: "Mısır seferiyle Memlük Devleti'ne son veren Osmanlı padişahı.", answers: ["yavuz sultan selim", "yavuz selim"], category: "Tarih", points: 10 },
    { letter: "Y", question: "Dünya gezegenini bir bütün olarak ifade eden Türkçe kelime.", answers: ["yerküre", "yer küre"], category: "Coğrafya", points: 10 },
    { letter: "Y", question: "1872'de kurulan ve dünyanın ilk millî parkı kabul edilen ABD parkı.", answers: ["yellowstone", "yellowstone ulusal parkı"], category: "Coğrafya", points: 10 },

    { letter: "Z", question: "Yunan mitolojisinde tanrıların kralı.", answers: ["zeus"], category: "Mitoloji", points: 10 },
    { letter: "Z", question: "Yaşayan en uzun kara hayvanı.", answers: ["zürafa"], category: "Doğa", points: 10 },
    { letter: "Z", question: "Mezopotamya'da basamaklı piramit biçiminde yapılan tapınak.", answers: ["ziggurat", "zigurat", "zikurat"], category: "Tarih", points: 10 },
    { letter: "Z", question: "Güneş'in yıl boyunca izlediği görünür yol üzerindeki on iki burç kuşağı.", answers: ["zodyak"], category: "Genel Kültür", points: 10 },
    { letter: "Z", question: "Taş kömürü madenciliğiyle tanınan Karadeniz ili.", answers: ["zonguldak"], category: "Coğrafya", points: 10 },
    { letter: "Z", question: "Beril mineralinin yeşil renkli ve değerli türü.", answers: ["zümrüt"], category: "Bilim", points: 10 },
];
